<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.37">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>4&nbsp; Chi-squares – Research Process for Music Psychologists</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./05-ttests.html" rel="next">
<link href="./03-inferential.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-7f8f88aac4f3542376d5c11b86a4c14d.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-9e3e5b9121e68b3f077afb32f2c64d95.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./04-chisquares.html">Part II: Basic inferential tests</a></li><li class="breadcrumb-item"><a href="./04-chisquares.html"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Chi-squares</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Research Process for Music Psychologists</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Part I: Introduction</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">A very brief introduction to R</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-descriptives.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Descriptive statistics</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-inferential.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Inferential statistics</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Part II: Basic inferential tests</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-chisquares.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Chi-squares</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-ttests.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">t-tests</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06-anovas.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">ANOVAs</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07-regressions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Linear relationships</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Part III: Advanced methods</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08-factorial-anovas.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Factorial ANOVAs</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./09-regressions-2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Regression continued</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./10-logistic.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Logistic regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./11-efa.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Exploratory factor analysis</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./12-medmod.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Mediation and Moderation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./13-nonpara.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Non-parametric tests</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./appendix.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Appendix</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#calculating-a-chi-square" id="toc-calculating-a-chi-square" class="nav-link active" data-scroll-target="#calculating-a-chi-square"><span class="header-section-number">4.1</span> Calculating a chi-square</a>
  <ul class="collapse">
  <li><a href="#categorical-data" id="toc-categorical-data" class="nav-link" data-scroll-target="#categorical-data"><span class="header-section-number">4.1.1</span> Categorical data</a></li>
  <li><a href="#the-chi-square-formula" id="toc-the-chi-square-formula" class="nav-link" data-scroll-target="#the-chi-square-formula"><span class="header-section-number">4.1.2</span> The chi-square formula</a></li>
  </ul></li>
  <li><a href="#the-chi-square-distribution" id="toc-the-chi-square-distribution" class="nav-link" data-scroll-target="#the-chi-square-distribution"><span class="header-section-number">4.2</span> The chi-square distribution</a>
  <ul class="collapse">
  <li><a href="#the-chi-square-distribution-1" id="toc-the-chi-square-distribution-1" class="nav-link" data-scroll-target="#the-chi-square-distribution-1"><span class="header-section-number">4.2.1</span> The chi-square distribution</a></li>
  <li><a href="#hypothesis-testing-in-chi-squares" id="toc-hypothesis-testing-in-chi-squares" class="nav-link" data-scroll-target="#hypothesis-testing-in-chi-squares"><span class="header-section-number">4.2.2</span> Hypothesis testing in chi-squares</a></li>
  <li><a href="#calculating-significance" id="toc-calculating-significance" class="nav-link" data-scroll-target="#calculating-significance"><span class="header-section-number">4.2.3</span> Calculating significance</a></li>
  </ul></li>
  <li><a href="#goodness-of-fit" id="toc-goodness-of-fit" class="nav-link" data-scroll-target="#goodness-of-fit"><span class="header-section-number">4.3</span> Goodness of fit</a>
  <ul class="collapse">
  <li><a href="#goodness-of-fit-tests" id="toc-goodness-of-fit-tests" class="nav-link" data-scroll-target="#goodness-of-fit-tests"><span class="header-section-number">4.3.1</span> Goodness of fit tests</a></li>
  <li><a href="#example" id="toc-example" class="nav-link" data-scroll-target="#example"><span class="header-section-number">4.3.2</span> Example</a></li>
  <li><a href="#calculating-2" id="toc-calculating-2" class="nav-link" data-scroll-target="#calculating-2"><span class="header-section-number">4.3.3</span> Calculating (\^2)</a></li>
  <li><a href="#using-r" id="toc-using-r" class="nav-link" data-scroll-target="#using-r"><span class="header-section-number">4.3.4</span> Using R</a></li>
  <li><a href="#output" id="toc-output" class="nav-link" data-scroll-target="#output"><span class="header-section-number">4.3.5</span> Output</a></li>
  </ul></li>
  <li><a href="#tests-of-independence" id="toc-tests-of-independence" class="nav-link" data-scroll-target="#tests-of-independence"><span class="header-section-number">4.4</span> Tests of independence</a>
  <ul class="collapse">
  <li><a href="#example-scenario" id="toc-example-scenario" class="nav-link" data-scroll-target="#example-scenario"><span class="header-section-number">4.4.1</span> Example scenario</a></li>
  <li><a href="#contingency-tables" id="toc-contingency-tables" class="nav-link" data-scroll-target="#contingency-tables"><span class="header-section-number">4.4.2</span> Contingency tables</a></li>
  <li><a href="#expected-frequencies" id="toc-expected-frequencies" class="nav-link" data-scroll-target="#expected-frequencies"><span class="header-section-number">4.4.3</span> Expected frequencies</a></li>
  <li><a href="#output-1" id="toc-output-1" class="nav-link" data-scroll-target="#output-1"><span class="header-section-number">4.4.4</span> Output</a></li>
  </ul></li>
  <li><a href="#effect-sizes-for-chi-squares" id="toc-effect-sizes-for-chi-squares" class="nav-link" data-scroll-target="#effect-sizes-for-chi-squares"><span class="header-section-number">4.5</span> Effect sizes for chi-squares</a>
  <ul class="collapse">
  <li><a href="#phi" id="toc-phi" class="nav-link" data-scroll-target="#phi"><span class="header-section-number">4.5.1</span> Phi</a></li>
  <li><a href="#cramers-v" id="toc-cramers-v" class="nav-link" data-scroll-target="#cramers-v"><span class="header-section-number">4.5.2</span> Cramer’s V</a></li>
  <li><a href="#interpretation" id="toc-interpretation" class="nav-link" data-scroll-target="#interpretation"><span class="header-section-number">4.5.3</span> Interpretation</a></li>
  <li><a href="#practice" id="toc-practice" class="nav-link" data-scroll-target="#practice"><span class="header-section-number">4.5.4</span> Practice</a></li>
  </ul></li>
  <li><a href="#bonus-mcnemars-test" id="toc-bonus-mcnemars-test" class="nav-link" data-scroll-target="#bonus-mcnemars-test"><span class="header-section-number">4.6</span> Bonus: McNemar’s Test</a>
  <ul class="collapse">
  <li><a href="#mcnemars-test" id="toc-mcnemars-test" class="nav-link" data-scroll-target="#mcnemars-test"><span class="header-section-number">4.6.1</span> McNemar’s test</a></li>
  <li><a href="#mathematical-basis" id="toc-mathematical-basis" class="nav-link" data-scroll-target="#mathematical-basis"><span class="header-section-number">4.6.2</span> Mathematical basis</a></li>
  <li><a href="#example-1" id="toc-example-1" class="nav-link" data-scroll-target="#example-1"><span class="header-section-number">4.6.3</span> Example</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./04-chisquares.html">Part II: Basic inferential tests</a></li><li class="breadcrumb-item"><a href="./04-chisquares.html"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Chi-squares</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Chi-squares</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<div class="cell">
<style type="text/css">
.math {
  font-size: x-large;
}
</style>
</div>
<p>While many of the things we are interested in when it comes to psychological research are continuously distributed (height, weight, reaction time, personality), there are many instances where we will need to work with data that is categorical. This can involve categorical independent variables (e.g.&nbsp;assigning participants to one or two groups) or categorical outcomes (e.g.&nbsp;responding yes or no). We’ll start with looking at relationships between these categorical variables, and testing for significant associations.</p>
<p>This module will see you diving deep into Jamovi again - so be prepared to get hands on with a bunch of data! Between the seminar, the worked examples and exercises there are at least 6 different datasets to play around with for this week!</p>
<p>By the end of this module you should be able to:</p>
<ul>
<li>Describe how a chi-square statistic is calculated</li>
<li>Conduct two forms of chi-square tests: goodness-of-fit and tests of independence</li>
<li>Calculate and interpret an appropriate effect size for tests of independence</li>
</ul>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="https://imgs.xkcd.com/comics/question_2x.png" class="img-fluid figure-img"></p>
<figcaption><a href="https://xkcd.com/1448/">xkcd: Question</a></figcaption>
</figure>
</div>
</div>
</div>
<section id="calculating-a-chi-square" class="level2" data-number="4.1">
<h2 data-number="4.1" class="anchored" data-anchor-id="calculating-a-chi-square"><span class="header-section-number">4.1</span> Calculating a chi-square</h2>
<div style="background-color: #f5f5f5;  padding: 1.75rem;">
<p>We’ll start this module off by briefly going through the basics of what research designs suit chi-square tests, as well as the basic maths underlying the first part of the statistical test.</p>
</div>
<section id="categorical-data" class="level3" data-number="4.1.1">
<h3 data-number="4.1.1" class="anchored" data-anchor-id="categorical-data"><span class="header-section-number">4.1.1</span> Categorical data</h3>
<p>As mentioned at the start of this module, chi-square tests are used when we work with <strong>categorical data</strong> - i.e., when we are dealing with <em>counts</em> of items or people, rather than continuous variables. Research questions focused on relationships or associations among categorical variables are suited to chi-square tests.</p>
<p>Every categorical variable will have <strong>levels</strong> (categories) within them. These are the different values that categorical variable can be. For example, biological sex is often coded with two levels: male and female. Or perhaps you might categorise socioeconomic status into three levels: low, medium and high bands. This is something that can form a core part of your research design. The most basic example is asking participants what their biological sex is - participants will respond with one of the two categories.</p>
<p>Alternatively, you can <em>create</em> categories from existing data. For example, many scales designed to assess psychological disorders such as depression and anxiety often have ‘cutoff’ points, where a certain score on the scale is indicative of a possible disorder. If you have everyone’s raw scores, you can convert these scores into categories depending on whether they are above or below these cutoff points (though this needs to be strongly justified).</p>
<p>All of this kind of data are amenable to chi-square tests, <em>if</em> you are interested in relationships between categorical variables. The family of chi-square tests basically work by comparing the <strong>observed values to</strong> the <strong>expected values</strong>. As the names imply, observed value simply means the number of observations we have in each category or level (i.e.&nbsp;what our data actually is). Expected values, on the other hand, are the number of things we would <em>expect</em> to see under the null hypothesis.</p>
<p>We can visualise categorical variables in two basic ways: a) a <strong>contingency table</strong> or b) a <strong>bar graph of counts</strong>. Below is the same set of data, shown in both forms:</p>
</section>
<section id="the-chi-square-formula" class="level3" data-number="4.1.2">
<h3 data-number="4.1.2" class="anchored" data-anchor-id="the-chi-square-formula"><span class="header-section-number">4.1.2</span> The chi-square formula</h3>
<p>To test whether a result is significant, remember that we need to calculate a test statistic, and see where that fits on its underlying distribution. Here, our test statistic is handily named the <strong>chi-square statistic</strong>. To calculate the chi-squared test statistic we use the following formula:</p>
<p><span class="math display">\[
\chi^2 = \Sigma \frac{(O-E)^2}{E}
\]</span></p>
<p>Where:</p>
<ul>
<li><p>O = <strong>observed value</strong></p></li>
<li><p>E = <strong>expected</strong> <strong>value</strong></p></li>
</ul>
<p>The English translation of that above formula can be described in four steps:</p>
<ol type="1">
<li><p>Calculate observed count - expected count</p></li>
<li><p>Square that difference</p></li>
<li><p>Divide it by the expected count</p></li>
<li><p>Do this for each cell, and add them all up</p></li>
</ol>
<p>We’ll look at this in more detail when we look at the actual tests. For the time being, here’s the key takeaway: have a look at the two graphs below, representing the observed and expected values of two different datasets.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="04-chisquares_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid figure-img" width="768"></p>
</figure>
</div>
</div>
</div>
<p>Have a think about the following:</p>
<ol type="1">
<li><p>What is each graph telling you?</p></li>
<li><p>The left graph appears to show noticeable differences between the observed and expected values. Based on the mathematical formula above, what will happen to the chi-square value?</p></li>
<li><p>Each graph represents one set of data. Based on your answers to a) and b) above, which one of the two would you expect to demonstrate a significant effect?</p></li>
</ol>
</section>
</section>
<section id="the-chi-square-distribution" class="level2" data-number="4.2">
<h2 data-number="4.2" class="anchored" data-anchor-id="the-chi-square-distribution"><span class="header-section-number">4.2</span> The chi-square distribution</h2>
<div style="background-color: #f5f5f5;  padding: 1.75rem;">
<p>On the previous page we introduced the formula for a chi-square test statistic. But what do we do with it? We’ll go through this below in detail, given that this is the first time we’re coming across an actual test. While a computer will do all of this stuff automatically, it’s useful to know the actual mechanisms underlying the test.</p>
</div>
<section id="the-chi-square-distribution-1" class="level3" data-number="4.2.1">
<h3 data-number="4.2.1" class="anchored" data-anchor-id="the-chi-square-distribution-1"><span class="header-section-number">4.2.1</span> The chi-square distribution</h3>
<p>Recall from Week 6 about how hypothesis tests work - we calculate a test statistic that conforms to a particular distribution, and we assess how likely our observed test statistic is (or greater) on this distribution, assuming the null hypothesis is true. This gives us the p-value for that test. With that in mind, the chi-square distribution that underlies the chi-square test looks something like this:</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="04-chisquares_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The shape of the chi-square distribution is only dependent on the degrees of freedom (<em>df</em>). We’ll look at how to calculate degrees of freedom for various tests, including the family of chi-square tests, as we move along the subject.</p>
<p>Here is the same set of lines above, but shown in their own plot this time:</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="04-chisquares_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>As you can hopefully see, the chi-square distribution is very heavily skewed at lower degrees of freedom (and therefore in smaller sample sizes). As degrees of freedom increase though, it approximates a normal distribution. For instance, here’s what the chi-square distribution looks like when <em>df</em> = 100:</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="04-chisquares_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="hypothesis-testing-in-chi-squares" class="level3" data-number="4.2.2">
<h3 data-number="4.2.2" class="anchored" data-anchor-id="hypothesis-testing-in-chi-squares"><span class="header-section-number">4.2.2</span> Hypothesis testing in chi-squares</h3>
<p>At this point, also recall that <em>p</em>-values are the probability that we would get our observed result (or greater), assuming the null hypothesis is true.</p>
<p>Here is our first application of this concept. When we use a chi-square test, we are performing the following basic steps:</p>
<ol type="1">
<li>Establish null and alternative hypotheses</li>
<li>Determine alpha level (in this case, <span class="math inline">\(\alpha\)</span> = .05 as always)</li>
<li>Calculate our test statistic - here, this is the chi-square statistic</li>
<li>Compare our chi-square test statistic against the chi-square distribution</li>
<li>Calculate how likely we would have seen our chi-square value or greater on this distribution a. Or, alternatively, establish a critical chi-square value - the value that must be crossed for a result to be significant</li>
</ol>
<p>We’ll expand on this more in the next couple of pages.</p>
</section>
<section id="calculating-significance" class="level3" data-number="4.2.3">
<h3 data-number="4.2.3" class="anchored" data-anchor-id="calculating-significance"><span class="header-section-number">4.2.3</span> Calculating significance</h3>
<p>Let’s say that we have a <em>df</em> of 5. How do we know where the critical chi-square value is?</p>
<p>For that, we consult a chi-square table. This table gives the critical chi-square value at a set degrees of freedom and alpha level. These are freely available online, but here’s a short excerpt. To read this table:</p>
<ul>
<li>The far-left column lists different degrees of freedom. We need to find the row that corresponds to <em>df</em> = 5.</li>
<li>Each column provides critical chi-squares at different alpha levels. We want to find the column that says .05.</li>
<li>The number at both of these points tells us the critical chi-square value.</li>
</ul>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="img/w7_chisq_table.png" class="img-fluid figure-img" width="573"></p>
</figure>
</div>
</div>
</div>
<p>So, for a <em>df</em> = 5 and an <span class="math inline">\(\alpha\)</span> = .05, the critical chi-square value is 11.07. If our own chi-square value is greater than this, the probability of that value or greater occurring (assuming the null) will be less than 5%; i.e.&nbsp;the boundary for statistical significance.</p>
<p>In picture form:</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="img/w7_chisq_df_5.png" class="img-fluid figure-img" width="900"></p>
</figure>
</div>
</div>
</div>
<p>Hopefully that makes sense - this kind of logic is pretty much identical to the other tests that we will cover in the coming weeks!</p>
</section>
</section>
<section id="goodness-of-fit" class="level2" data-number="4.3">
<h2 data-number="4.3" class="anchored" data-anchor-id="goodness-of-fit"><span class="header-section-number">4.3</span> Goodness of fit</h2>
<div style="background-color: #f5f5f5;  padding: 1.75rem;">
<p>Now that we’ve covered the conceptual groundwork for chi-square tests in general, we can now start looking at actual tests that can help us answer research questions. The most basic chi-square test is the goodness of fit test.</p>
</div>
<section id="goodness-of-fit-tests" class="level3" data-number="4.3.1">
<h3 data-number="4.3.1" class="anchored" data-anchor-id="goodness-of-fit-tests"><span class="header-section-number">4.3.1</span> Goodness of fit tests</h3>
<p>Goodness of fit tests are used when we want to compare a set of categorical data against a hypothetical distribution. Goodness of fit tests require one categorical variable - as the name implies, a goodness of fit test looks at whether the proportions of categories/levels in this variable fits an expected distribution. In other words, do our counts for each category match what we would expect under the null?</p>
<p>“Distribution” in this context means probability distributions, and can apply to a wide range of scenarios. For the purposes of what we’re learning here, we’ll stick to a question along the lines of: “do the categories of variable X align with their expected probabilities”?</p>
</section>
<section id="example" class="level3" data-number="4.3.2">
<h3 data-number="4.3.2" class="anchored" data-anchor-id="example"><span class="header-section-number">4.3.2</span> Example</h3>
<p>An example question that we look at in the seminar is Do Skittle bags have an even number of each colour? In the seminar, we go through whether or not a random bag has an even split of colours.</p>
<p>Here on Canvas, we’ll now tackle their equally delicious rivals, M&amp;Ms.&nbsp;The data and analysis come courtesy of Rick Wicklin, a data analyst at SAS (who also make statistics software). You can read his full blog here: <a href="https://blogs.sas.com/content/iml/2017/02/20/proportion-of-colors-mandms.html">The distribution of colors for plain M&amp;M candies</a>. We’ll be recreating Rick’s first analysis here. We’re sticking with the candy theme because a) they’re delicious and b) the M&amp;Ms are a great way to introduce what to do when expected proportions are not equal.</p>
<p>M&amp;Ms come in six colours: red, blue, green, brown, orange and yellow. Unlike Skittles, these colours are not distributed equally within each bag of M&amp;Ms.&nbsp;In 2008, Mars (the parent company) published the following percentage breakdown of colours:</p>
<ul>
<li>13% red</li>
<li>20% orange</li>
<li>14% yellow</li>
<li>16% green</li>
<li>24% blue</li>
<li>13% brown</li>
</ul>
<p>Rick collected his data in 2017, and so was interested in seeing if the proportions observed in his 2017 sample of M&amp;Ms aligned with the distribution of colours listed in 2008.</p>
<p>A goodness of fit is the perfect test for this scenario because:</p>
<ul>
<li>We are making a claim about a distribution</li>
<li>Our variable (colour) is categorical</li>
<li>A chi-square goodness of fit will allow us to test whether the distribution of colours in a sample of M&amp;Ms aligns with the published proportions.</li>
</ul>
<p>Here’s our dataset:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>mnm_data <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="fu">here</span>(<span class="st">"data"</span>, <span class="st">"week_7"</span>, <span class="st">"W7_M&amp;M.csv"</span>))</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(mnm_data)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 2
     id colour
  &lt;dbl&gt; &lt;chr&gt; 
1     1 Red   
2     2 Red   
3     3 Red   
4     4 Red   
5     5 Red   
6     6 Red   </code></pre>
</div>
</div>
</section>
<section id="calculating-2" class="level3" data-number="4.3.3">
<h3 data-number="4.3.3" class="anchored" data-anchor-id="calculating-2"><span class="header-section-number">4.3.3</span> Calculating (\^2)</h3>
<p>In goodness of fit tests, we first calculated the expected frequencies. In this example though, the expected proportions aren’t equal - and so we have to be mindful of this when calculating expected values. See the expected count cell for Red M&amp;Ms for how expected value is worked out in this instance.</p>
<p>We can draw this up in table form alongside our own data:</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Colour</th>
<th style="text-align: right;">Observed</th>
<th style="text-align: right;">Expected proportion</th>
<th style="text-align: left;">Expected count</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Blue</td>
<td style="text-align: right;">133</td>
<td style="text-align: right;">0.24</td>
<td style="text-align: left;">170.88</td>
</tr>
<tr class="even">
<td style="text-align: left;">Brown</td>
<td style="text-align: right;">96</td>
<td style="text-align: right;">0.13</td>
<td style="text-align: left;">92.56</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Green</td>
<td style="text-align: right;">139</td>
<td style="text-align: right;">0.16</td>
<td style="text-align: left;">113.92</td>
</tr>
<tr class="even">
<td style="text-align: left;">Orange</td>
<td style="text-align: right;">133</td>
<td style="text-align: right;">0.20</td>
<td style="text-align: left;">142.4</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Red</td>
<td style="text-align: right;">108</td>
<td style="text-align: right;">0.13</td>
<td style="text-align: left;"><span class="math inline">\(712 \times 0.13 = 92.56\)</span></td>
</tr>
<tr class="even">
<td style="text-align: left;">Yellow</td>
<td style="text-align: right;">103</td>
<td style="text-align: right;">0.14</td>
<td style="text-align: left;">99.68</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Then we would use the formula we saw on the previous page to calculate a chi-square statistic. However, since we’re doing this in R we’ll skip the manual maths.</p>
<p><span class="math display">\[
\chi^2 = \Sigma \frac{(O-E)^2}{E}
\]</span></p>
<p>If we have a look at the observed vs expected values, we might have a good idea of what’s going on already:</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="04-chisquares_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="using-r" class="level3" data-number="4.3.4">
<h3 data-number="4.3.4" class="anchored" data-anchor-id="using-r"><span class="header-section-number">4.3.4</span> Using R</h3>
<p>The relevant function for doing a chi-square test in R is the <code>chisq.test()</code> function.<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a></p>
<p>By default, the <code>chisq.test()</code> function in R will assume that your categories have an equal chance of happening. However, in this instance we know that the colours are not evenly distributed. To ensure the proper probabilities are set beforehand, this needs to be specified by giving the <code>p</code> argument within <code>chisq.test()</code>. Note that the order of the expected probabilities needs to match the order they appear in the dataset (R will generally order these alphabetically unless told otherwise):</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># This pulls the relevant variable directly</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>w7_mnm_table <span class="ot">&lt;-</span> <span class="fu">table</span>(mnm_data<span class="sc">$</span>colour)</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>w7_mnm_chisq <span class="ot">&lt;-</span> <span class="fu">chisq.test</span>(w7_mnm_table, </span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>                            <span class="at">p =</span> <span class="fu">c</span>(<span class="fl">0.24</span>, <span class="fl">0.13</span>, <span class="fl">0.16</span>, <span class="fl">0.20</span>, <span class="fl">0.13</span>, <span class="fl">0.14</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>R Note: Manually ordering variables
</div>
</div>
<div class="callout-body-container callout-body">
<p>If you need to order your variable a certain way, you should use the <code>factor()</code> function. You will need to specify a <code>levels</code> argument, which describes the ordering of the categories/groups, and optionally a <code>labels</code> argument which gives each one a label. Both arguments take vectors, i.e.&nbsp;<code>labels = c("1", "2", "3")</code>.</p>
</div>
</div>
</section>
<section id="output" class="level3" data-number="4.3.5">
<h3 data-number="4.3.5" class="anchored" data-anchor-id="output"><span class="header-section-number">4.3.5</span> Output</h3>
<p>Here’s what our output looks like. First is our table of proportions. This can be really useful in laying out the data and seeing where the differences between observed and expected proportions might lie.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>w7_mnm_chisq<span class="sc">$</span>observed</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
  Blue  Brown  Green Orange    Red Yellow 
   133     96    139    133    108    103 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>w7_mnm_chisq<span class="sc">$</span>expected</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Blue  Brown  Green Orange    Red Yellow 
170.88  92.56 113.92 142.40  92.56  99.68 </code></pre>
</div>
</div>
<p>Next, here is our test output. The result is significant (<em>p</em> = .004), suggesting that the 2017 bag of M&amp;Ms does not follow the same distribution of colours as the 2008 values. (If you read the rest of Rick’s blog post, it turns out that somewhere between 2008 and 2017 they changed where M&amp;Ms are made, and actually split production across two factories that produce different distributions of colours. Rick eventually found out that his bag most likely came from one of the plants, although Mars has not made these proportions public like they used to.)</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>w7_mnm_chisq</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Chi-squared test for given probabilities

data:  w7_mnm_table
X-squared = 17.353, df = 5, p-value = 0.003877</code></pre>
</div>
</div>
<p>Here is an example write-up of these results:</p>
<div style="background-color: #cce3c8;  padding: 1.75rem;">
<p>A chi-square test of goodness of fit was conducted to see whether the number of M&amp;Ms aligned with the expected proportions published in 2008. There was a significant difference between the observed and expected proportions (<span class="math inline">\(\chi^2\)</span>(5, <em>N</em> = 712) = 17.35, <em>p</em> = .004). There were more green M&amp;Ms and less blue M&amp;Ms than expected.</p>
</div>
</section>
</section>
<section id="tests-of-independence" class="level2" data-number="4.4">
<h2 data-number="4.4" class="anchored" data-anchor-id="tests-of-independence"><span class="header-section-number">4.4</span> Tests of independence</h2>
<div style="background-color: #f5f5f5;  padding: 1.75rem;">
<p>The next chi-square test we will cover is probably the most common - the chi-square test of independence. Here, we move from one categorical variable to two.</p>
</div>
<p>Chi square tests of independence are used when we want to test whether two categorical variables are associated with each other (i.e.&nbsp;show a relationship). Some examples of this question might take on the following:</p>
<ul>
<li>Is smoking history (yes/no) associated with lung cancer diagnosis? (yes/no)</li>
<li>Is there an association between gender and employment status?</li>
</ul>
<section id="example-scenario" class="level3" data-number="4.4.1">
<h3 data-number="4.4.1" class="anchored" data-anchor-id="example-scenario"><span class="header-section-number">4.4.1</span> Example scenario</h3>
<p>We’ll start off with a very basic example. In the below dataset, children from several schools were surveyed regarding what instrument they played. This dataset focuses on two instruments that have historically been seen as gendered (e.g.&nbsp;see Abeles 2009) - clarinet and drums. The sex of the child playing the instrument was also recorded.</p>
<p>Our research question is: is there an association between sex and instrument choice?</p>
<p>Dataset:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>instrument_data <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="fu">here</span>(<span class="st">"data"</span>, <span class="st">"week_7"</span>, <span class="st">"W7_instruments.csv"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 122 Columns: 3
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (2): instrument, sex
dbl (1): id

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(instrument_data)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 3
     id instrument sex  
  &lt;dbl&gt; &lt;chr&gt;      &lt;chr&gt;
1     1 clarinet   M    
2     2 clarinet   M    
3     3 clarinet   M    
4     4 clarinet   F    
5     5 clarinet   F    
6     6 clarinet   M    </code></pre>
</div>
</div>
</section>
<section id="contingency-tables" class="level3" data-number="4.4.2">
<h3 data-number="4.4.2" class="anchored" data-anchor-id="contingency-tables"><span class="header-section-number">4.4.2</span> Contingency tables</h3>
<p>The primary way of ‘drawing up’ categorical data, particularly when two variables are involved, is to draw a contingency table. A contingency table is a two-way table that shows how many participants/items/objects fall under each combination of our two variables. Here is a contingency table of our data below:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>w7_instrument_table <span class="ot">&lt;-</span> <span class="fu">table</span>(instrument_data<span class="sc">$</span>instrument,</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>                             instrument_data<span class="sc">$</span>sex)</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>w7_instrument_table  <span class="sc">%&gt;%</span></span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">addmargins</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>          
             F   M Sum
  clarinet  51  48  99
  drums      6  17  23
  Sum       57  65 122</code></pre>
</div>
</div>
</section>
<section id="expected-frequencies" class="level3" data-number="4.4.3">
<h3 data-number="4.4.3" class="anchored" data-anchor-id="expected-frequencies"><span class="header-section-number">4.4.3</span> Expected frequencies</h3>
<p>To calculate expected frequencies in a two-way contingency table (i.e.&nbsp;a test of independence), we use the following formula:</p>
<p><span class="math display">\[
E = \frac{R \times C}{N}
\]</span></p>
<p>Where R = row total and column = column total.</p>
<p>Let’s put this into practice with girls who play the clarinet (highlighted above). The row total for this cell is 99 (i.e.&nbsp;total number of clarinet players). The column total is 57 (total number of girls). To calculate an expected value for this cell, we would therefore calculate the following:</p>
<p><span class="math inline">\(E = \frac{99 \times 57}{122}\)</span></p>
<p>This works out to be roughly 46.25 - which means that we would expect roughly 46 female clarinet players. We then go through and calculate this for each cell, so that we have all of our expected values.</p>
<p>Once we’ve done that, we can then calculate our chi-square test statistic using the same formula as always:</p>
<p><span class="math display">\[
\chi^2 = \Sigma \frac{(O-E)^2}{E}
\]</span></p>
</section>
<section id="output-1" class="level3" data-number="4.4.4">
<h3 data-number="4.4.4" class="anchored" data-anchor-id="output-1"><span class="header-section-number">4.4.4</span> Output</h3>
<p>Here’s our output! Firstly, our contingency table:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>w7_inst_chisq <span class="ot">&lt;-</span> <span class="fu">chisq.test</span>(w7_instrument_table, <span class="at">correct =</span> <span class="cn">FALSE</span>)</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>w7_inst_chisq<span class="sc">$</span>observed</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>          
            F  M
  clarinet 51 48
  drums     6 17</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>w7_inst_chisq<span class="sc">$</span>expected</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>          
                 F       M
  clarinet 46.2541 52.7459
  drums    10.7459 12.2541</code></pre>
</div>
</div>
<p>Next is our chi-square test output. As you can see, our test of independence suggests a significant result (<em>p</em> = .03). In other words, we reject the null hypothesis that there is no association between instrument and sex.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>w7_inst_chisq</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's Chi-squared test

data:  w7_instrument_table
X-squared = 4.848, df = 1, p-value = 0.02768</code></pre>
</div>
</div>
<p>Like the previous page, here’s an example write-up of our results:</p>
<div style="background-color: #cce3c8;  padding: 1.75rem;">
<p>A chi-square test of association was conducted to examine whether there was an association between sex and instrument choice. A significant association was observed (<span class="math inline">\(\chi^2\)</span>(1, <em>N</em> = 122) = 4.85, <em>p</em> = .028; Cramer’s <em>V</em> = .199). There were more male drummers and less female drummers than expected.</p>
</div>
<p>Note that as part of the write-up above, you would also include a brief interpretation of the effect size - but we will discuss this on the next page.</p>
</section>
</section>
<section id="effect-sizes-for-chi-squares" class="level2" data-number="4.5">
<h2 data-number="4.5" class="anchored" data-anchor-id="effect-sizes-for-chi-squares"><span class="header-section-number">4.5</span> Effect sizes for chi-squares</h2>
<div style="background-color: #f5f5f5;  padding: 1.75rem;">
<p>This is the first time we’re coming across effect sizes for any test - thankfully, we start with relatively easy ones to wrap your head around. We will cover two effect sizes: phi (<span class="math inline">\(\phi\)</span>) and Cramer’s <em>V</em>, both of which apply when conducting a test of independence.</p>
</div>
<section id="phi" class="level3" data-number="4.5.1">
<h3 data-number="4.5.1" class="anchored" data-anchor-id="phi"><span class="header-section-number">4.5.1</span> Phi</h3>
<p>Phi (<span class="math inline">\(\phi\)</span>) is an effect size for chi-squares that applies only to 2x2 designs. The formula for phi is:</p>
<p><span class="math display">\[
\phi = \sqrt{\frac{\chi^2}{n}}
\]</span></p>
<p>Essentially, it is the chi-square test statistic divided by the sample size, which is then square rooted. Again, it only works for 2x2 designs - i.e.&nbsp;each categorical variable can only have two categories within it.</p>
</section>
<section id="cramers-v" class="level3" data-number="4.5.2">
<h3 data-number="4.5.2" class="anchored" data-anchor-id="cramers-v"><span class="header-section-number">4.5.2</span> Cramer’s V</h3>
<p>Cramer’s <em>V</em> is another effect size for chi-squares, but one that can be used for anything beyond a 2x2 design as well. The formula for Cramer’s <em>V</em> is similar:</p>
<p><span class="math display">\[
V = \sqrt{\frac{\chi^2}{n(k-1)}}
\]</span> Here, <em>k</em> refers to the number of groups in the variable with the lowest number of groups. So for example, in a 2x3 design, one variable has 2 levels and the other has 3; <em>k</em> = 2 in this instance.</p>
<p>Phi and Cramer’s <em>V</em> can both be calculated in R with the following functions from the <code>effectsize</code> package, a handy package that will calculate many common effect size measures. Like <code>chisq.test()</code>, both functions will work if you give them a contingency table. Helpfully, both functions calculate 95% CIs.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>effectsize<span class="sc">::</span><span class="fu">phi</span>(w7_instrument_table, <span class="at">adjust =</span> <span class="cn">FALSE</span>, <span class="at">alternative =</span> <span class="st">"two.sided"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Phi  |       95% CI
-------------------
0.20 | [0.00, 0.38]</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>effectsize<span class="sc">::</span><span class="fu">cramers_v</span>(w7_instrument_table, <span class="at">adjust =</span> <span class="cn">FALSE</span>, <span class="at">alternative =</span> <span class="st">"two.sided"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Cramer's V |       95% CI
-------------------------
0.20       | [0.00, 0.38]</code></pre>
</div>
</div>
</section>
<section id="interpretation" class="level3" data-number="4.5.3">
<h3 data-number="4.5.3" class="anchored" data-anchor-id="interpretation"><span class="header-section-number">4.5.3</span> Interpretation</h3>
<p>Phi and Cramer’s <em>V</em> are essentially both correlation coefficients (more on this in Week 10). Both phi and Cramer’s <em>V</em> can only be between 0 and 1. For this subject, the size of Cramer’s <em>V</em> and phi can be interpreted as follows:</p>
<ul>
<li>If the effect size = .10, the effect is small</li>
<li>If effect size = .30, the effect is medium</li>
<li>If effect size = .50 or above, the effect is large</li>
</ul>
</section>
<section id="practice" class="level3" data-number="4.5.4">
<h3 data-number="4.5.4" class="anchored" data-anchor-id="practice"><span class="header-section-number">4.5.4</span> Practice</h3>
<p>Given the following results from a 2x2 chi-square test of independence:</p>
<ul>
<li><span class="math inline">\(\chi^2\)</span> = 5.45</li>
<li><em>N</em> = 46</li>
</ul>
<p>Calculate both phi and Cramer’s <em>V</em>. (You should get the same answer, but have a go at trying it both ways!)</p>
</section>
</section>
<section id="bonus-mcnemars-test" class="level2" data-number="4.6">
<h2 data-number="4.6" class="anchored" data-anchor-id="bonus-mcnemars-test"><span class="header-section-number">4.6</span> Bonus: McNemar’s Test</h2>
<div style="background-color: #f5f5f5;  padding: 1.75rem;">
<p>The chi-square test of independence, as the name implies, relies on the assumption of independence - that variable A is statistically independent of B. But what happens if we have a relationship that doesn’t meet this assumption? The most common kind is when data is <em>paired</em> or <em>repeated</em>, i.e.&nbsp;participants are measured on the same variable twice. McNemar’s test allows us to apply chi-square techniques to this kind of data.</p>
</div>
<section id="mcnemars-test" class="level3" data-number="4.6.1">
<h3 data-number="4.6.1" class="anchored" data-anchor-id="mcnemars-test"><span class="header-section-number">4.6.1</span> McNemar’s test</h3>
<p><strong>McNemar’s test</strong> is used for when you have repeated-measures categorical data. Specifically, it applies to a 2x2 repeated measures contingency table. This will apply when you have one sample tested <strong>twice</strong> on a <strong>binary outcome</strong>. The most common example of this is a yes/no outcome, before and after something (e.g.&nbsp;an intervention.</p>
<p>McNemar’s test will apply to situations where you have one sample tested twice like this:</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: left;">Timepoint 2 - A</th>
<th style="text-align: left;">Timepoint 2 - B</th>
<th style="text-align: left;">Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">Timepoint 1 - A</td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Timepoint 1 - B</td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">Total</td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
<section id="mathematical-basis" class="level3" data-number="4.6.2">
<h3 data-number="4.6.2" class="anchored" data-anchor-id="mathematical-basis"><span class="header-section-number">4.6.2</span> Mathematical basis</h3>
<p>Consider the table above. We can formulate the cells between each combination of predictors, and their totals, as follows:</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: left;">Timepoint 2 - A</th>
<th style="text-align: left;">Timepoint 2 - B</th>
<th style="text-align: left;">Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">Timepoint 1 - A</td>
<td style="text-align: left;">a</td>
<td style="text-align: left;">b</td>
<td style="text-align: left;">a + b</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Timepoint 1 - B</td>
<td style="text-align: left;">c</td>
<td style="text-align: left;">d</td>
<td style="text-align: left;">c + d</td>
</tr>
<tr class="even">
<td style="text-align: left;">Total</td>
<td style="text-align: left;">a + c</td>
<td style="text-align: left;">b + d</td>
<td style="text-align: left;">N</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Essentially, in this instance cell <em>a</em> represents the number of cases/participants in T1-A and T2-A, <em>b</em> is T1-A and T2-B etc etc. Each cell has two <strong>marginal probabilities</strong>, which are the row and column totals corresponding to that cell. Cell <em>a</em>, for example, has marginal probabilities of <em>a + b</em> (the row total) and <em>a + c</em> (the column total). Cell d has marginal probabilities of <em>c + d</em> and <em>b + d</em>.</p>
<p>The null hypothesis in this scenario is that the <strong>two marginal properties for each outcome are the same</strong>. This is a principle known as marginal homogeneity. In essence, the McNemar test tests the hypothesis that the proportion of participants responding A beforehand is the same at that responding A afterwards. The marginal probability in this instance is a + b (proportion of response A at timepoint 1) and a + c (proportion of response A at timepoint 2).</p>
<p>The same hypothesis applies to the proportion of participant saying B before and after, corresponding to cell d.&nbsp;In this case, the marginal probabilities are c + d (time 1) and b + d (time 2).</p>
<p>We can express this null hypothesis like this:</p>
<p><span class="math display">\[
p_a + p_b = p_a + p_c
\]</span></p>
<p><span class="math display">\[
p_b + p_d = p_c + p_d
\]</span></p>
<p>We can simplify both equations by removing identical terms from both sides of the equation. You might see then that both equations cancel out to simply be:</p>
<p><span class="math display">\[
p_b = p_c
\]</span></p>
<p>That, in effect, is our null hypothesis - that the probability of cell b is identical to cell c! So now we can express our null and alternative hypotheses:</p>
<ul>
<li><span class="math inline">\(H_0: p_b = p_c\)</span></li>
<li><span class="math inline">\(H_1: p_b \neq p_c\)</span></li>
</ul>
<p>Our chi-square test statistic is calculated as follows:</p>
<p><span class="math display">\[
\chi^2 = \frac{(b-c)^2}{b+c}
\]</span></p>
<p>And then from here on, the process of deriving a <em>p</em>-value is identical to a regular chi-square test, with the exception that the df is always df = 1 (remember we have a 2 x 2 table, and the formula for a df in a two-way chi-square test is to subtract 1 from each and multiply them together).</p>
</section>
<section id="example-1" class="level3" data-number="4.6.3">
<h3 data-number="4.6.3" class="anchored" data-anchor-id="example-1"><span class="header-section-number">4.6.3</span> Example</h3>
<p>Below is a fictional dataset from 70 registered voters in a fictional country. The 70 voters were asked whether they intended to vote for the current government twice: before event X happened in the government and after event X. Their responses were recorded as simple Yes-No answers.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>w7_voting <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="fu">here</span>(<span class="st">"data"</span>, <span class="st">"week_7"</span>, <span class="st">"W7_voting.csv"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 71 Columns: 3
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (2): before, after
dbl (1): id

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
</div>
<p>Here is a contingency table of our data:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>w7_voting_table <span class="ot">&lt;-</span> <span class="fu">table</span>(w7_voting<span class="sc">$</span>before, w7_voting<span class="sc">$</span>after) </span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>w7_voting_table <span class="sc">%&gt;%</span></span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">addmargins</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>     
      No Yes Sum
  No  18  28  46
  Yes 11  13  24
  Sum 29  41  70</code></pre>
</div>
</div>
<p>We can identify our b = 28 and our c = 11. We can calculate a relevant chi-squared test statistic using the formula above:</p>
<p><span class="math display">\[
\chi^2 = \frac{(b-c)^2}{b+c}
\]</span></p>
<p><span class="math display">\[
\chi^2 = \frac{(28-11)^2}{28+11}
\]</span> <span class="math display">\[
\chi^2 = \frac{(17)^2}{39}
\]</span></p>
<p><span class="math display">\[
\chi^2 = 7.41
\]</span></p>
<p>If we were doing this fully by hand, we could consult a chi-squared table and see what the relevant <em>p</em>-value would be with this chi-squared value and a df = 1. However, we’ll skip straight to Jamovi. A McNemar test can be run in R using the <code>mcnemar.test()</code> function in base R:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>w7_voting_mcn <span class="ot">&lt;-</span> <span class="fu">mcnemar.test</span>(w7_voting_table, <span class="at">correct =</span> <span class="cn">FALSE</span>)</span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>w7_voting_mcn</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    McNemar's Chi-squared test

data:  w7_voting_table
McNemar's chi-squared = 7.4103, df = 1, p-value = 0.006485</code></pre>
</div>
</div>
<p>The output looks like this, and confirms that there is a significant change in proportions before and after event (<span class="math inline">\(\chi^2\)</span>(1, <em>N</em> = 70) = 7.41, <em>p</em> = .006). Based on the original values of <em>b</em> and <em>c</em>, we can infer that this might be because more people changed their vote from No -&gt; Yes than the other way round.</p>


</section>
</section>
<section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes">
<hr>
<ol>
<li id="fn1"><p>There is an analogous function called <code>chisq_test()</code> in the <code>rstatix</code> package, but the base R <code>chisq.test()</code> is easy enough to learn.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./03-inferential.html" class="pagination-link" aria-label="Inferential statistics">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Inferential statistics</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./05-ttests.html" class="pagination-link" aria-label="t-tests">
        <span class="nav-page-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">t-tests</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>Copyright 2026, Daniel Yeom</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
      <ul class="footer-items list-unstyled">
    <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/danyeom">
      <i class="bi bi-github" role="img">
</i> 
    </a>
  </li>  
</ul>
    </div>
  </div>
</footer>




</body></html>