<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.36">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>6&nbsp; ANOVAs – Research Process for Music Psychologists</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./07-regressions.html" rel="next">
<link href="./05-ttests.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-845c23b38eaddc0f92fda52bfe77a8c8.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-9e3e5b9121e68b3f077afb32f2c64d95.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./04-chisquares.html">Part II: Basic inferential tests</a></li><li class="breadcrumb-item"><a href="./06-anovas.html"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">ANOVAs</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Research Process for Music Psychologists</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Part I: Introduction</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">A very brief introduction to R</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-descriptives.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Descriptive statistics</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-inferential.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Inferential statistics</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Part II: Basic inferential tests</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-chisquares.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Chi-squares</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-ttests.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">t-tests</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06-anovas.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">ANOVAs</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07-regressions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Linear relationships</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Part III: Advanced methods</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08-factorial-anovas.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Factorial ANOVAs</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./09-regressions-2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Regression continued</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./10-logistic.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Logistic regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./11-efa.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Exploratory factor analysis</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./12-medmod.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Mediation and Moderation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./13-nonpara.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Non-parametric tests</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./appendix.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Appendix</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#anovas-and-the-f-distribution" id="toc-anovas-and-the-f-distribution" class="nav-link active" data-scroll-target="#anovas-and-the-f-distribution"><span class="header-section-number">6.1</span> Anovas and the <em>F</em>-distribution</a>
  <ul class="collapse">
  <li><a href="#the-basic-logic-of-anovas" id="toc-the-basic-logic-of-anovas" class="nav-link" data-scroll-target="#the-basic-logic-of-anovas"><span class="header-section-number">6.1.1</span> The basic logic of ANOVAs</a></li>
  <li><a href="#the-f-distribution" id="toc-the-f-distribution" class="nav-link" data-scroll-target="#the-f-distribution"><span class="header-section-number">6.1.2</span> The <em>F</em>-distribution</a></li>
  <li><a href="#f-statistic-tables" id="toc-f-statistic-tables" class="nav-link" data-scroll-target="#f-statistic-tables"><span class="header-section-number">6.1.3</span> <em>F</em>-statistic tables</a></li>
  </ul></li>
  <li><a href="#the-anova-table" id="toc-the-anova-table" class="nav-link" data-scroll-target="#the-anova-table"><span class="header-section-number">6.2</span> The ANOVA table</a>
  <ul class="collapse">
  <li><a href="#the-anova-table-1" id="toc-the-anova-table-1" class="nav-link" data-scroll-target="#the-anova-table-1"><span class="header-section-number">6.2.1</span> The ANOVA table</a></li>
  <li><a href="#sums-of-squares" id="toc-sums-of-squares" class="nav-link" data-scroll-target="#sums-of-squares"><span class="header-section-number">6.2.2</span> Sums of squares</a></li>
  <li><a href="#degrees-of-freedom" id="toc-degrees-of-freedom" class="nav-link" data-scroll-target="#degrees-of-freedom"><span class="header-section-number">6.2.3</span> Degrees of freedom</a></li>
  <li><a href="#mean-squares" id="toc-mean-squares" class="nav-link" data-scroll-target="#mean-squares"><span class="header-section-number">6.2.4</span> Mean squares</a></li>
  <li><a href="#calculating-f" id="toc-calculating-f" class="nav-link" data-scroll-target="#calculating-f"><span class="header-section-number">6.2.5</span> Calculating <em>F</em></a></li>
  <li><a href="#putting-it-all-together" id="toc-putting-it-all-together" class="nav-link" data-scroll-target="#putting-it-all-together"><span class="header-section-number">6.2.6</span> Putting it all together</a></li>
  <li><a href="#consulting-the-f-table" id="toc-consulting-the-f-table" class="nav-link" data-scroll-target="#consulting-the-f-table"><span class="header-section-number">6.2.7</span> Consulting the <em>F</em>-table</a></li>
  </ul></li>
  <li><a href="#multiple-comparisons" id="toc-multiple-comparisons" class="nav-link" data-scroll-target="#multiple-comparisons"><span class="header-section-number">6.3</span> Multiple comparisons</a>
  <ul class="collapse">
  <li><a href="#post-hoc-tests" id="toc-post-hoc-tests" class="nav-link" data-scroll-target="#post-hoc-tests"><span class="header-section-number">6.3.1</span> Post-hoc tests</a></li>
  <li><a href="#the-multiple-comparisons-problem" id="toc-the-multiple-comparisons-problem" class="nav-link" data-scroll-target="#the-multiple-comparisons-problem"><span class="header-section-number">6.3.2</span> The multiple comparisons problem</a></li>
  <li><a href="#correction-methods" id="toc-correction-methods" class="nav-link" data-scroll-target="#correction-methods"><span class="header-section-number">6.3.3</span> Correction methods</a></li>
  <li><a href="#post-hocs-in-r" id="toc-post-hocs-in-r" class="nav-link" data-scroll-target="#post-hocs-in-r"><span class="header-section-number">6.3.4</span> Post-hocs in R</a></li>
  </ul></li>
  <li><a href="#eta-squared" id="toc-eta-squared" class="nav-link" data-scroll-target="#eta-squared"><span class="header-section-number">6.4</span> Eta-squared</a>
  <ul class="collapse">
  <li><a href="#eta-squared-and-variance" id="toc-eta-squared-and-variance" class="nav-link" data-scroll-target="#eta-squared-and-variance"><span class="header-section-number">6.4.1</span> Eta-squared and variance</a></li>
  <li><a href="#an-example" id="toc-an-example" class="nav-link" data-scroll-target="#an-example"><span class="header-section-number">6.4.2</span> An example</a></li>
  <li><a href="#interpreting-eta-squared" id="toc-interpreting-eta-squared" class="nav-link" data-scroll-target="#interpreting-eta-squared"><span class="header-section-number">6.4.3</span> Interpreting eta-squared</a></li>
  </ul></li>
  <li><a href="#one-way-anova" id="toc-one-way-anova" class="nav-link" data-scroll-target="#one-way-anova"><span class="header-section-number">6.5</span> One-way ANOVA</a>
  <ul class="collapse">
  <li><a href="#the-basic-one-way-anova" id="toc-the-basic-one-way-anova" class="nav-link" data-scroll-target="#the-basic-one-way-anova"><span class="header-section-number">6.5.1</span> The basic one-way ANOVA</a></li>
  <li><a href="#example-data" id="toc-example-data" class="nav-link" data-scroll-target="#example-data"><span class="header-section-number">6.5.2</span> Example data</a></li>
  <li><a href="#assumption-checks" id="toc-assumption-checks" class="nav-link" data-scroll-target="#assumption-checks"><span class="header-section-number">6.5.3</span> Assumption checks</a></li>
  <li><a href="#output" id="toc-output" class="nav-link" data-scroll-target="#output"><span class="header-section-number">6.5.4</span> Output</a></li>
  <li><a href="#post-hoc-tests-1" id="toc-post-hoc-tests-1" class="nav-link" data-scroll-target="#post-hoc-tests-1"><span class="header-section-number">6.5.5</span> Post-hoc tests</a></li>
  </ul></li>
  <li><a href="#one-way-repeated-measures-anova" id="toc-one-way-repeated-measures-anova" class="nav-link" data-scroll-target="#one-way-repeated-measures-anova"><span class="header-section-number">6.6</span> One-way repeated measures ANOVA</a>
  <ul class="collapse">
  <li><a href="#repeated-measures-anovas" id="toc-repeated-measures-anovas" class="nav-link" data-scroll-target="#repeated-measures-anovas"><span class="header-section-number">6.6.1</span> Repeated measures ANOVAs</a></li>
  <li><a href="#example-data-1" id="toc-example-data-1" class="nav-link" data-scroll-target="#example-data-1"><span class="header-section-number">6.6.2</span> Example data</a></li>
  <li><a href="#assumption-checks-1" id="toc-assumption-checks-1" class="nav-link" data-scroll-target="#assumption-checks-1"><span class="header-section-number">6.6.3</span> Assumption checks</a></li>
  <li><a href="#anova-output" id="toc-anova-output" class="nav-link" data-scroll-target="#anova-output"><span class="header-section-number">6.6.4</span> ANOVA output</a></li>
  <li><a href="#post-hoc-tests-2" id="toc-post-hoc-tests-2" class="nav-link" data-scroll-target="#post-hoc-tests-2"><span class="header-section-number">6.6.5</span> Post-hoc tests</a></li>
  <li><a href="#alternative-using-rstatix" id="toc-alternative-using-rstatix" class="nav-link" data-scroll-target="#alternative-using-rstatix"><span class="header-section-number">6.6.6</span> Alternative using <code>rstatix</code></a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./04-chisquares.html">Part II: Basic inferential tests</a></li><li class="breadcrumb-item"><a href="./06-anovas.html"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">ANOVAs</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">ANOVAs</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p><em>t</em>-tests, as we saw last week, were a simple way of comparing a continuous outcome between two groups or conditions (i.e.&nbsp;one categorical variable with two levels). However, it’s also common to compare across three or more groups when doing real research. To test this kind of hypothesis where we have three or more groups, we need to turn to a different method - the ANOVA. ANOVAs are useful when you have one categorical IV with 3+ levels, and one continuous DV.</p>
<p>The ANOVA is perhaps one of the most common statistical tests you will see in music psychology literature, in part because they generalise to a lot of research designs. In many respects, this week is fairly important in terms of knowing how to conduct an ANOVA and when. We’ll only be stepping through the basics this week, but there are some really important fundamentals to cover here.</p>
<p>It’s also common to analyse two independent variables against one dependent variable. These too can be done using ANOVAs. While we won’t go into this in this module, there will be an Extension Module that deals with this separately - check it out sometime around Week 10/11 if you’re interested.</p>
<p>By the end of this module you should be able to:</p>
<ul>
<li>Understand and describe the conceptual basis of an analysis of variance</li>
<li>Describe how an ANOVA is calculated</li>
<li>Conduct both one-way ANOVAs and one-way repeated ANOVAs, including their assumption tests</li>
<li>Interpret the output of the ANOVAs and report their findings</li>
</ul>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="https://imgs.xkcd.com/comics/third_way_2x.png" class="img-fluid figure-img"></p>
<figcaption><a href="https://xkcd.com/1285/">xkcd: Third Way</a></figcaption>
</figure>
</div>
</div>
</div>
<section id="anovas-and-the-f-distribution" class="level2" data-number="6.1">
<h2 data-number="6.1" class="anchored" data-anchor-id="anovas-and-the-f-distribution"><span class="header-section-number">6.1</span> Anovas and the <em>F</em>-distribution</h2>
<div style="background-color: #f5f5f5;  padding: 1.75rem;">
<p>Just as we’ve done so for chi-squares and <em>t</em>-tests, let’s begin with an overview of the mathematical and conceptual underpinnings of the ANOVA.</p>
</div>
<section id="the-basic-logic-of-anovas" class="level3" data-number="6.1.1">
<h3 data-number="6.1.1" class="anchored" data-anchor-id="the-basic-logic-of-anovas"><span class="header-section-number">6.1.1</span> The basic logic of ANOVAs</h3>
<p>As we said in the introductory page, ANOVA stands for <strong>AN</strong>alysis <strong>O</strong>f <strong>VA</strong>riance. This essentially sums up how an ANOVA works in principle. ANOVAs can be used when analysing a categorical IV with two or more groups (typically 3+) and a continuous DV. As the setup suggests, ANOVAs are a good way of comparing different groups on a singular outcome.</p>
<p>The most basic hypotheses for an ANOVA center around whether or not the means between groups are significantly different, i.e.:</p>
<ul>
<li><span class="math inline">\(H_0\)</span>: The means between groups are not significantly different. (i.e.&nbsp;<span class="math inline">\(\mu_1 = \mu_2 = ... \mu_k\)</span>)</li>
<li><span class="math inline">\(H_1\)</span>: The means between groups are significantly different. (i.e.<span class="math inline">\(\mu_1 \neq \mu_2 \neq ... \mu_k\)</span>)</li>
</ul>
<p>How do we test for this? The basic logic of the ANOVA is this: Whenever we have data that we categorise into different groups, we end up with two key sources of variability, or variance: variance that exists between groups, and variance that exists within groups:</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="06-anovas_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid figure-img" width="768"></p>
</figure>
</div>
</div>
</div>
<p>Pretend that the three curves above represent data covering three different groups, and that we’ve hypothesised that there are three different means. Collectively, this data has a certain amount of variance.</p>
<p>The first fundamental to recognise is that this total variance can be broken down into variance between groups and variance within groups:</p>
<p><span class="math display">\[
Variance_{total} = Variance_{between} + Variance_{within}
\]</span></p>
<p>The variability between the groups would simply be the variance between the blue curve and the orange curve - in other words, how far apart the two sets of data are (in a simplistic sense). The within-group variance, on the other hand, is how much variance there is within each curve. If there is a lot of within-group variance within each curve, that would mean that (thinking back to Module 5) each group’s curve would be spread widely.</p>
<p>If you’re following the logic of this so far, the consequences of high within-group variance might be obvious - the two curves would significantly overlap. In contrast, if the between-group variance is far higher than the within-group variance, the curves may not overlap much at all - suggesting that the means of the two groups really are different.</p>
<p>This forms the basis of the ANOVA’s <em>F</em>-test, which is a ratio of variance:</p>
<p><span class="math display">\[
F = \frac{Variance_{between}}{Variance_{within}}
\]</span></p>
<p>We will see this more in practice on the next page, but the <em>F</em>-statistic, which we use as part of significance testing in ANOVAs, is calculated by simply dividing the between-group variance by the within-group variance.</p>
</section>
<section id="the-f-distribution" class="level3" data-number="6.1.2">
<h3 data-number="6.1.2" class="anchored" data-anchor-id="the-f-distribution"><span class="header-section-number">6.1.2</span> The <em>F</em>-distribution</h3>
<p>Like the other tests we’ve encountered so far, ANOVAs have their own underlying distribution. In this instance, this is the <em>F</em> distribution, which describes how the <em>F</em>-statistic behaves. We won’t go far into the maths around this, but the key here is that the <em>F</em> distribution is characterised by two sets of degrees of freedom: one that relates to the between-groups variance/effect, and one that relates to the within-groups variance. One thing to note here is the terminology in the headers of each graph: the first number in the brackets refers to the between-groups variance, while the second number refers to the within-groups variance.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="06-anovas_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="f-statistic-tables" class="level3" data-number="6.1.3">
<h3 data-number="6.1.3" class="anchored" data-anchor-id="f-statistic-tables"><span class="header-section-number">6.1.3</span> <em>F</em>-statistic tables</h3>
<p>And, once again, we have a special <em>F</em>-table to determine critical <em>F</em> values, given two degrees of freedom values. However, given that we have two degrees of freedom the process is a little bit more complicated. Most <em>F</em>-stat tables actually provide multiple tables, corresponding to different alpha levels. For now, we will always use the table corresponding to alpha = 0.05, a snippet of which is below:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">include_graphics</span>(<span class="fu">here</span>(<span class="st">"img/w9_f-table.png"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="img/w9_f-table.png" class="img-fluid figure-img" width="1072"></p>
</figure>
</div>
</div>
</div>
<p>To read this table, you need to know both degrees of freedom (more on how to find that on the next page). The columns, marked df1, refer to the first df value (between-groups), while the rows correspond to the second df value (within-groups).</p>
<p>So, for example, if we have an <em>F</em>-test with degrees of freedom of (4, 10), we would first need to find the column that corresponds to 4 (our df1), and then the row that corresponds to df2 = 10. Reading the cell at the intersection would give us a critical <em>F</em>-statistic of 3.48; this is the value our <em>F</em>-statistic would need to be greater than to be significant at the <em>p</em> &lt; .05 level.</p>
</section>
</section>
<section id="the-anova-table" class="level2" data-number="6.2">
<h2 data-number="6.2" class="anchored" data-anchor-id="the-anova-table"><span class="header-section-number">6.2</span> The ANOVA table</h2>
<div style="background-color: #f5f5f5;  padding: 1.75rem;">
<p>Every time we do an ANOVA, there are actually a raft of calculations that have to occur in order to get our test statistic and <em>p</em>-value. Statistical software will display all of this in the form of an ANOVA table, which we cover below.</p>
<p>Don’t stress too much about the maths here - while the quiz does include one question about this, the question itself isn’t difficult (and you won’t be expected to do any of this by hand otherwise). The reason why we go through this, however, is to demonstrate the conceptual logic from the previous page.</p>
</div>
<section id="the-anova-table-1" class="level3" data-number="6.2.1">
<h3 data-number="6.2.1" class="anchored" data-anchor-id="the-anova-table-1"><span class="header-section-number">6.2.1</span> The ANOVA table</h3>
<p>On the previous page, we talked in depth about how the <em>F</em> statistic is calculated, and what shapes the overall distribution. But how do we actually calculate all of that stuff to begin with from raw data? Enter the ANOVA table, a beautiful (remember, beauty is subjective) way of calculating this information and laying it all out to see.</p>
<p>The basic ANOVA table looks like this, which you will see on any statistical package you use.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th>Sums of squares (SS)</th>
<th>Degrees of freedom (df)</th>
<th>Mean square (MS)</th>
<th>F</th>
<th><em>p</em></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Group (our effect)</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td>Error/Residual</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td>Total</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
</tbody>
</table>
<p>A couple of terminology-related things here.</p>
<ul>
<li>‘Group’ in this context is our independent variable (i.e.&nbsp;the effect of group)- this is our between-subject variance.</li>
<li>‘Error’ or ‘Residual’ is the within-group variance.</li>
</ul>
<p>Let’s use the below data to calculate this by hand.</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Group 1</th>
<th style="text-align: left;">Group 2</th>
<th style="text-align: left;">Group 3</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">1</td>
<td style="text-align: left;">2</td>
<td style="text-align: left;">5</td>
</tr>
<tr class="even">
<td style="text-align: left;">2</td>
<td style="text-align: left;">4</td>
<td style="text-align: left;">8</td>
</tr>
<tr class="odd">
<td style="text-align: left;">3</td>
<td style="text-align: left;">5</td>
<td style="text-align: left;">6</td>
</tr>
<tr class="even">
<td style="text-align: left;">2</td>
<td style="text-align: left;">3</td>
<td style="text-align: left;">7</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Mean: 2</td>
<td style="text-align: left;">Mean: 3.5</td>
<td style="text-align: left;">Mean: 6</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>The grand mean (i.e.&nbsp;the mean across all 12 pieces of data) is 4. Keep this in mind.</p>
<p>Time to strap in - there are a lot of formulae involved!</p>
</section>
<section id="sums-of-squares" class="level3" data-number="6.2.2">
<h3 data-number="6.2.2" class="anchored" data-anchor-id="sums-of-squares"><span class="header-section-number">6.2.2</span> Sums of squares</h3>
<p>The sum of squares quantifies how far each observation is from the average - just like how it is calculated in the formula for standard deviations. For an ANOVA, we have two sets of SS to calculate - one for the between-groups term, and one for the within-groups/error.</p>
<p><strong>Between</strong></p>
<p>The formula for the between-groups sum of squares (<span class="math inline">\(SS_b\)</span>) is:</p>
<p><span class="math display">\[
SS_b = \Sigma n(\bar x - \bar X)^2
\]</span></p>
<p>In words, this means:</p>
<ul>
<li>Take each group’s mean (<span class="math inline">\(\bar x\)</span>), and subtract them from the grand mean (<span class="math inline">\(\bar X\)</span>)</li>
<li>Square that difference</li>
<li>Multiply it by n, the size of each group</li>
<li>Add them all up.</li>
</ul>
<p>Let’s do that for our fictional data. Our group means are Group 1 = 2, Group 2 = 3.5 and Group 3 = 6.5. <span class="math display">\[SS_b = 4(2-4)^2 + 4(3.5-4)^2 + 4(6.5-4)^2\]</span></p>
<p><span class="math display">\[SS_b = (4 \times 4) + (4 \times 0.25) + (4 \times 6.25)\]</span> <span class="math display">\[SS_b = 42\]</span></p>
<p><strong>Within</strong></p>
<p>For the within-group sum of squares, the formula is:</p>
<p><span class="math display">\[
SS_w = \Sigma (x - \bar x)^2
\]</span></p>
<p>This one is a bit more tedious. It means:</p>
<ul>
<li>Take each observation (<span class="math inline">\(x\)</span>), and subtract them from their group mean (<span class="math inline">\(\bar x\)</span>)</li>
<li>Square that difference</li>
<li>Add them all up.</li>
</ul>
<p>So for our data, it would look something like.. <span class="math display">\[
\begin{aligned}
SS_w = (1-2)^2 + (2-2)^2 + (3-2)^2 + (2-2)^2 + \\
(2-3.5)^2 + (4-3.5)^2 + (5-3.5)^2 + (3-3.5)^2 + \\
(5-6.5)^2 + (8-6.5)^2 + (6-6.5)^2 + (7-6.5)^2
\end{aligned}
\]</span> <span class="math display">\[SS_w = 12\]</span>.</p>
</section>
<section id="degrees-of-freedom" class="level3" data-number="6.2.3">
<h3 data-number="6.2.3" class="anchored" data-anchor-id="degrees-of-freedom"><span class="header-section-number">6.2.3</span> Degrees of freedom</h3>
<p>Because we have a term for between-groups and within-groups effects, we also have degrees of freedom for both (think back to the previous page). Thankfully, unlike the mess above the formulae here are relatively simple.</p>
<p><strong>Between</strong></p>
<p>The between-groups df is given as:</p>
<p><span class="math display">\[
df_b = k - 1
\]</span></p>
<p>Where k = the number of groups. So, in our data, <span class="math inline">\(df_b = 3 -1 = 2\)</span> (as we have 3 groups).</p>
<p><strong>Within</strong></p>
<p>The within-groups df is given as:</p>
<p><span class="math display">\[
df_b = N - k
\]</span></p>
<p>Where k = the number of groups, and <em>N</em> is the total sample size (in our case, 12). So <span class="math inline">\(df_w = 12 -3 = 9\)</span> (as we have 3 groups and 12 data points in total).</p>
</section>
<section id="mean-squares" class="level3" data-number="6.2.4">
<h3 data-number="6.2.4" class="anchored" data-anchor-id="mean-squares"><span class="header-section-number">6.2.4</span> Mean squares</h3>
<p>The mean squares is another value for variance that essentially standardises the sum of squares by the degrees of freedom. The formula for MS between and within is the same:</p>
<p><span class="math display">\[
MS = \frac{SS}{df}
\]</span></p>
<p>We’ve calculated SS and df for both our between and within-groups effects, so we can substitute these values in to calculate a mean square value for both:</p>
<p><span class="math display">\[MS_b = \frac{SS_b}{df_b}\]</span> <span class="math display">\[MS_w = \frac{SS_w}{df_w}\]</span></p>
<p>Putting in our values that we calculated earlier, we get:</p>
<p><span class="math display">\[MS_b = \frac{42}{2}\]</span> <span class="math display">\[MS_w = \frac{12}{9}\]</span></p>
<p>This gives us <span class="math inline">\(MS_b = 21\)</span> and <span class="math inline">\(MS_w = 1.33\)</span>.</p>
</section>
<section id="calculating-f" class="level3" data-number="6.2.5">
<h3 data-number="6.2.5" class="anchored" data-anchor-id="calculating-f"><span class="header-section-number">6.2.5</span> Calculating <em>F</em></h3>
<p>Remember on the previous page, how we talked about the <em>F</em>-statistic being a ratio between two variances (between divided by within)? That’s exactly what we’re going to do next, using our calculated mean-square values:</p>
<p><span class="math display">\[
F = \frac{MS_b}{MS_w}
\]</span></p>
<p>This gives us:</p>
<p><span class="math display">\[
F = \frac{21}{1.33} = 15.75
\]</span></p>
</section>
<section id="putting-it-all-together" class="level3" data-number="6.2.6">
<h3 data-number="6.2.6" class="anchored" data-anchor-id="putting-it-all-together"><span class="header-section-number">6.2.6</span> Putting it all together</h3>
<p>Phew! Now we’ve calculated everything we need to for our ANOVA - in essence, we’ve done the majority of the ANOVA by hand. Let’s put all of our values into the table below:</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 21%">
<col style="width: 23%">
<col style="width: 26%">
<col style="width: 18%">
<col style="width: 6%">
<col style="width: 3%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: left;">Sums of squares (SS)</th>
<th style="text-align: left;">Degrees of freedom (df)</th>
<th style="text-align: left;">Mean square (MS)</th>
<th style="text-align: left;">F</th>
<th style="text-align: left;">p</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Group (our effect)</td>
<td style="text-align: left;">42</td>
<td style="text-align: left;">2</td>
<td style="text-align: left;">21</td>
<td style="text-align: left;">15.75</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">Error/Residual</td>
<td style="text-align: left;">12</td>
<td style="text-align: left;">9</td>
<td style="text-align: left;">1.33</td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Total</td>
<td style="text-align: left;">54</td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Before we move on, it’s also worth noting that <span class="math inline">\(SS_b + SS_w = SS_{total}\)</span> ; this goes back to the fundamental we discussed on the previous page, where an ANOVA breaks down total variance into between and within-groups variance.</p>
</section>
<section id="consulting-the-f-table" class="level3" data-number="6.2.7">
<h3 data-number="6.2.7" class="anchored" data-anchor-id="consulting-the-f-table"><span class="header-section-number">6.2.7</span> Consulting the <em>F</em>-table</h3>
<p>Now that we have our observed <em>F</em>-value, we can now consult an <em>F</em>-table and use our two degrees of freedom to find out what our critical <em>F</em>-value is (setting alpha = .05):</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="img/w9_f-table.png" class="img-fluid figure-img" width="1072"></p>
</figure>
</div>
</div>
</div>
<p>Reading the column for df1 = 2, and the row for df2 = 9, we get a critical <em>F</em>-statistic of 4.2565. Now we can say that because our observed test statistic (15.75) is greater than this critical value, our ANOVA is significant at the alpha = .05 level.</p>
<p>In reality, like many of the other tests, we would calculate a <em>p</em>-value by observing where our test statistic falls on the <em>F</em>-distribution, and the associated probability of getting that value or greater. Our software will do all of this stuff for us, but it helps to know exactly how an ANOVA works!</p>
<p>If you want to calculate the <em>p</em>-value manurally in R though, this is entirely possible using the <code>pf()</code> function:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pf</span>(<span class="at">q =</span> <span class="fl">15.75</span>, <span class="at">df1 =</span> <span class="dv">2</span>, <span class="at">df2 =</span> <span class="dv">9</span>, <span class="at">lower.tail =</span> <span class="cn">FALSE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.001149592</code></pre>
</div>
</div>
</section>
</section>
<section id="multiple-comparisons" class="level2" data-number="6.3">
<h2 data-number="6.3" class="anchored" data-anchor-id="multiple-comparisons"><span class="header-section-number">6.3</span> Multiple comparisons</h2>
<div style="background-color: #f5f5f5;  padding: 1.75rem;">
<p>On this page we talk about what happens after a significant ANOVA result, as well as some more detail about the multiple comparisons problem, and how it can be accounted for.</p>
</div>
<section id="post-hoc-tests" class="level3" data-number="6.3.1">
<h3 data-number="6.3.1" class="anchored" data-anchor-id="post-hoc-tests"><span class="header-section-number">6.3.1</span> Post-hoc tests</h3>
<p>The ANOVA table on the previous page allows us to calculate by hand whether there is a significant effect of our IV. However, it doesn’t tell us where that difference lies. Remember, we’re comparing at least three groups with each other - so we need some way of figuring out where the actual significant differences between means are.</p>
<p>Enter post-hoc comparisons (post-hoc = after the fact). These are essentially a series of <em>t</em>-tests where we compare each group with each other. So, if we have groups A, B and C, and we get a significant omnibus ANOVA that tells us there is a significant difference somewhere in those means, we would run post-hoc comparisons by running individual <em>t</em>-tests on A vs B, then B vs C, then A vs C.</p>
<p>However, we can’t just do this blindly, and there’s a good reason why…</p>
</section>
<section id="the-multiple-comparisons-problem" class="level3" data-number="6.3.2">
<h3 data-number="6.3.2" class="anchored" data-anchor-id="the-multiple-comparisons-problem"><span class="header-section-number">6.3.2</span> The multiple comparisons problem</h3>
<p>In Module 6, we talked a fair bit about Type I and II error rates - i.e., the rate of making a false positive and false negative judgement respectively. Here, we’ll focus on Type I error.</p>
<p>Recall that whenever we do a hypothesis test, we set a value for alpha, which forms our significance level. Alpha is essentially the probability of Type I errors we are willing to accept in a given test. In other words, when we use the conventional alpha = .05 as our criterion for significance, we are saying that we’re willing to accept a Type I error occurring 5% of the time - or 1 in 20.</p>
<p>This becomes problematic when we have to conduct multiple tests at once, like what we have to do in an ANOVA. For example, let’s say a variable has 5 levels - A, B, C, D and E. If we ran an ANOVA on this data and found a significant omnibus effect, we would want to find out where that effect is. But that means that we’d have to compare A, B, C, D and E all against each other, in a round-robin tournament way (e.g.&nbsp;A vs B, then A vs C…). Where this becomes an issue is that each comparison will have its own 5% Type I error rate (assuming we use alpha = .05). So in this scenario, the Type I error rate will stack with each new comparison, meaning that our overall Type I error rate will climb higher and higher. This means that the chance of finding a false positive will increase (see graph below).</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="06-anovas_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="384"></p>
</figure>
</div>
</div>
</div>
<p>This overall rate of Type I errors is called the family-wise error rate (FWER). ‘Family’ in this context refers to a family of comparisons - like the comparison across A to E that we saw above.</p>
</section>
<section id="correction-methods" class="level3" data-number="6.3.3">
<h3 data-number="6.3.3" class="anchored" data-anchor-id="correction-methods"><span class="header-section-number">6.3.3</span> Correction methods</h3>
<p>One way of dealing with this is to correct the <em>p</em>-values to set the family-wise error rate back to 5%. We’ll go through three main types (two of which are already covered in the seminar).</p>
<p><strong>Tukey’s HSD</strong></p>
<p>Tukey’s Honest Significant Differences (Tukey HSD for short) is appropriate specifically for post-hoc tests after ANOVAs. It essentially works by first calculating the largest possible difference between each group’s means, then using that to calculate a critical mean difference. Any mean difference that is greater than this critical threshold is significant.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>How does the Tukey test work?
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Tukey’s HSD works very similarly in principle to a <em>t</em>-test, although the exact maths involved are slightly different. The test statistic for a Tukey test is called <em>q</em> which denotes the Studentized range distribution (a specific distribution). For a given comparison between two group means, the formula for <em>q</em> is:</p>
<p><span class="math display">\[
q = \frac{|M_1 - M_2|}{SE}
\]</span></p>
<p>Where <span class="math inline">\(M_1\)</span> and <span class="math inline">\(M_2\)</span> denote the means of groups 1 and 2, and SE denotes the standard error of the sum of the means. The <em>q</em>-statistic is then compared to a Studentized range distribution to estimate a <em>p</em>-value for that comparison. The shape of the Studentized range distribution is determined by alpha, <em>k</em> (the number of groups being compared) and <em>df</em> (in this case, the **error degrees of freedom***).</p>
</div>
</div>
</div>
<p><strong>Bonferroni</strong></p>
<p>The Bonferroni correction is a method that can be used both within ANOVAs and in more general contexts. The Bonferroni correction works by multiplying each <em>p</em>-value in a set of comparisons by the number of comparisons (i.e.&nbsp;the number of <em>p</em>-values).</p>
<p>For example, if a set of comparisons gives the following <em>p</em>-values: 0.05, 0.25 and 0.10, we would apply a Bonferroni correction by multiplying each <em>p</em>-value by 3 (as there are 3 <em>p</em>-values) to get 0.15, 0.75 and 0.30 respectively.</p>
<p>(Note: in reality, Bonferroni works by dividing alpha by the number of comparisons, i.e.&nbsp;0.05/3 - but for the purpose of significance testing, the maths works out to be the same).</p>
<p><strong>Holm</strong></p>
<p>The Holm correction is another correction method. In this method, each <em>p</em>-value is first ranked from smallest to largest. and then numbered in a descending fashion. Using the same <em>p</em>-values as above, we would get 0.05, 0.10 and 0.25. The <em>p</em> = .05 would be ranked as 3, the <em>p</em> = .10 would be 2 and <em>p</em> = .25 would be 1.</p>
<p>You then multiply the <em>p</em>-value by its rank, like the table below, to get your adjusted <em>p</em>-values:</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Original p-value</th>
<th style="text-align: left;">Sorted p-value</th>
<th style="text-align: left;">Rank</th>
<th style="text-align: left;">p-value x rank</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">0.05</td>
<td style="text-align: left;">0.05</td>
<td style="text-align: left;">3</td>
<td style="text-align: left;">0.15</td>
</tr>
<tr class="even">
<td style="text-align: left;">0.25</td>
<td style="text-align: left;">0.10</td>
<td style="text-align: left;">2</td>
<td style="text-align: left;">0.20</td>
</tr>
<tr class="odd">
<td style="text-align: left;">0.10</td>
<td style="text-align: left;">0.25</td>
<td style="text-align: left;">1</td>
<td style="text-align: left;">0.25</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>The Bonferroni procedure is very conservative, in that it may actually overcorrect (and subsequently reject too many); the Holm correction still corrects the overall FWER without also increasing the overall Type II rate as well.</p>
</section>
<section id="post-hocs-in-r" class="level3" data-number="6.3.4">
<h3 data-number="6.3.4" class="anchored" data-anchor-id="post-hocs-in-r"><span class="header-section-number">6.3.4</span> Post-hocs in R</h3>
<p>To just get adjusted <em>p</em>-values, we can use the function <code>pairwise.t.test()</code>. This needs three arguments:</p>
<ol type="1">
<li><code>x</code> refers to the column of data for the outcome, expressed as <code>data$x</code>.</li>
<li><code>g</code> refers to the group/IV, again as <code>data$g</code>.</li>
<li><code>p.adjust.method</code> refers to the adjustment method. Note this argument does not allow Tukey adjustments: only Bonferroni and Holm are allowed.</li>
</ol>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pairwise.t.test</span>(<span class="at">x =</span> w9_slices<span class="sc">$</span>rating, <span class="at">g =</span> w9_slices<span class="sc">$</span>group, <span class="at">p.adjust.method =</span> <span class="st">"bonferroni"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pairwise comparisons using t tests with pooled SD 

data:  w9_slices$rating and w9_slices$group 

        caramel lemon 
lemon   0.6866  -     
vanilla 0.0541  0.0017

P value adjustment method: bonferroni </code></pre>
</div>
</div>
<p>A more powerful and flexible method is using the <code>emmeans</code> package. <code>emmeans</code> stands for estimated marginal means, which are model-derived estimates of each group’s mean. Simple effects tests are generally run on the estimate marginal means, and thus this package allows us a handy way to run these comparisons.</p>
<p>There are two steps to using <code>emmeans</code>:</p>
<ol type="1">
<li>Define the estimated marginal means for the post-hocs.</li>
</ol>
<p>This is simple to do. We call the <code>emmeans()</code> function, which will set up all comparisons for the post-hoc. This function needs two arguments at minimum:</p>
<ul>
<li>The <code>aov</code> model name, and</li>
<li>The variable (i.e.&nbsp;the groups) from which you are comparing levels against. This is given as <code>~ group</code>, where group denotes our IV.</li>
</ul>
<p>Imagine an ANOVA model named <code>model_aov</code>, with variable <code>A</code> that defines the groups in our ANOVA. Our first step would be to set up the comparisons using <code>emmeans()</code> like below:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>model_em <span class="ot">&lt;-</span> <span class="fu">emmeans</span>(model_aov, <span class="sc">~</span> A)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<ol start="2" type="1">
<li>Generate pairwise comparisons for the post-hoc.</li>
</ol>
<p>Continuing on from the example above, we can use the <code>pairs()</code> function on our EM object, <code>model_em</code>, to run the post-hocs. <code>infer = TRUE</code> will generate confidence intervals for the difference in EM means. By default this will be set at 95% confidence, which is typically what we want.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pairs</span>(model_em, <span class="at">infer =</span> <span class="cn">TRUE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>If we want to adjust the <em>p</em>-values at this stage, we can give <code>pairs()</code> an additional argument <code>adjust</code>, with the name of the adjustment method as a string. <code>pairs()</code> will let you use Tukey, Bonferroni and Holm adjustments.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pairs</span>(model_em, <span class="at">infer =</span> <span class="cn">TRUE</span>, <span class="at">adjust =</span> <span class="st">"holm"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Optionally, to do this all in one go we could simply pipe from <code>emmeans()</code> to <code>pairs()</code> as follows:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">emmeans</span>(model_aov, <span class="sc">~</span> A) <span class="sc">%&gt;%</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pairs</span>(<span class="at">infer =</span> <span class="cn">TRUE</span>, <span class="at">adjust =</span> <span class="st">"holm"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
</section>
<section id="eta-squared" class="level2" data-number="6.4">
<h2 data-number="6.4" class="anchored" data-anchor-id="eta-squared"><span class="header-section-number">6.4</span> Eta-squared</h2>
<div style="background-color: #f5f5f5;  padding: 1.75rem;">
<p>Time to go over a new effect size measure! This time, we use eta-squared (<span class="math inline">\(\eta^2\)</span>) as an effect size for ANOVAs.</p>
</div>
<section id="eta-squared-and-variance" class="level3" data-number="6.4.1">
<h3 data-number="6.4.1" class="anchored" data-anchor-id="eta-squared-and-variance"><span class="header-section-number">6.4.1</span> Eta-squared and variance</h3>
<p>At the start of this module, we introduced the concept of how ANOVA partitions total variance into both between and within-subject variance:</p>
<p><span class="math display">\[
Variance_{total} = Variance_{between} + Variance_{within}
\]</span></p>
<p>This partitioning allows for a simple but important way of calculating effect sizes for ANOVAs. If we’re interested in the effect of our IV (group, which is between-subject variance), we simply need to know how much of the total variance is explained by this variable.</p>
<p>This is <strong>eta-squared</strong> (<span class="math inline">\(\eta^2\)</span>), our effect size for ANOVAs. Eta-squared gives us a <strong>percentage of how much variance in the DV can be attributed to the IV</strong>. So an eta-squared of .778 means that 77.8% of the total variance in the outcome variable/DV is because of the IV variable/main effect. It is calculated as follows:</p>
<p><span class="math display">\[
\eta^2 = \frac{SS_{effect}}{SS_t}
\]</span></p>
<p>In other words, we divide the sum of squares for the main effect by the total sum of squares. For repeated-measures ANOVAs, the formula is the same in practice (i.e.&nbsp;divide the SS in the top row in the ANOVA table by the total).</p>
<p>A related version of this is <strong>partial eta-squared</strong> (<span class="math inline">\(\eta^2_p\)</span>). This describes the effect of the IV <em>after</em> accounting for the variance explained by other factors. This is not so relevant for one-way designs - regular and partial eta-squared will give the same answer - but becomes more relevant when you move into factorial designs where you have more than one IV.</p>
<p>The formula for partial eta-squared is:</p>
<p><span class="math display">\[
\eta^2_p = \frac{SS_{effect}}{SS_{effect} + SS_{error}}
\]</span></p>
<p>Where <span class="math inline">\(SS_{error}\)</span> is the sums of squares for the error/residual term in an ANOVA. In general, it’s good practice to default to at least reporting partial eta-squared. Again, in a one-way ANOVA this will give the same answer as regular eta-squared, but in a factorial design (where you have more than one IV) it will give a more precise estimate of each variable’s effect size.</p>
<p>One more variant you will see is <em>generalised</em> eta-squared <span class="math inline">\(\eta^2_g\)</span>, which is similar to the partial variant. While partial eta-squared is great, it is sensitive to design - in other words, what variables are included in the analysis will influence the calculation of <span class="math inline">\(\eta^2_p\)</span>, meaning that it is only really comparable across studies of similar design. However, not every design will manipulate every predictor (e.g.&nbsp;gender), and so generalised eta-squared (<span class="math inline">\(\eta^2_G\)</span>) can handle this. This effect size is best used in meta-analyses.</p>
<p>To calculate eta-squared using R, there are two ways as per usual. The first is by using tthe <code>anova_test()</code> function in <code>rstatix</code>. By default, <code>anova_test()</code> (and other ANOVA-related packages in R) will calculate <em>generalised</em> eta squared (labelled <code>ges</code> in the output). If you want partial eta-squared, you just need to give <code>anova_test()</code> the extra argument <code>effect.size = "pes"</code> as follows:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>w9_memory <span class="sc">%&gt;%</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">anova_test</span>(<span class="at">dv =</span> memory_score, <span class="at">wid =</span> Participant, <span class="at">within =</span> time, <span class="at">effect.size =</span> <span class="st">"pes"</span>) </span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>ANOVA Table (type III tests)

$ANOVA
  Effect DFn DFd       F        p p&lt;.05   pes
1   time   2 188 132.625 1.19e-36     * 0.585

$`Mauchly's Test for Sphericity`
  Effect     W     p p&lt;.05
1   time 0.939 0.054      

$`Sphericity Corrections`
  Effect   GGe       DF[GG]    p[GG] p[GG]&lt;.05   HFe       DF[HF]    p[HF]
1   time 0.943 1.89, 177.21 1.05e-34         * 0.961 1.92, 180.72 2.45e-35
  p[HF]&lt;.05
1         *</code></pre>
</div>
</div>
<p>Note that as mentioned above, partial eta-squared and regular eta-squared are equivalent in a one-way ANOVA of any kind, so using this is ok.</p>
<p>Otherwise, our trusty <code>effectsize</code> package provides functions for calculating effect sizes in R. We use a function called - you guessed it - <code>eta_squared()</code>. This function works in very much the same way as the other <code>effectsize</code> family of functions do - you need to give them an anova model to calculate effect sizes for.</p>
<p>Here is an example with a one-way ANOVA, which we will look at on the next page:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">eta_squared</span>(w9_slices_aov, <span class="at">alternative =</span> <span class="st">"two.sided"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>For one-way between subjects designs, partial eta squared is equivalent
  to eta squared. Returning eta squared.</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code># Effect Size for ANOVA

Parameter | Eta2 |       95% CI
-------------------------------
group     | 0.19 | [0.03, 0.35]</code></pre>
</div>
</div>
</section>
<section id="an-example" class="level3" data-number="6.4.2">
<h3 data-number="6.4.2" class="anchored" data-anchor-id="an-example"><span class="header-section-number">6.4.2</span> An example</h3>
<p>Here’s the ANOVA table we worked out by hand in Section 9.3:</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 21%">
<col style="width: 23%">
<col style="width: 26%">
<col style="width: 18%">
<col style="width: 6%">
<col style="width: 3%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: left;">Sums of squares (SS)</th>
<th style="text-align: left;">Degrees of freedom (df)</th>
<th style="text-align: left;">Mean square (MS)</th>
<th style="text-align: left;">F</th>
<th style="text-align: left;">p</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Group (our effect)</td>
<td style="text-align: left;">42</td>
<td style="text-align: left;">2</td>
<td style="text-align: left;">21</td>
<td style="text-align: left;">15.75</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">Error/Residual</td>
<td style="text-align: left;">12</td>
<td style="text-align: left;">9</td>
<td style="text-align: left;">1.33</td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Total</td>
<td style="text-align: left;">54</td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
</tbody>
</table>
</div>
</div>
<p>If we were to calculate an eta-squared value for this, we would use SS effect (42) and SSt (54) like so:</p>
<p><span class="math display">\[
\eta^2 = \frac{42}{54} = .778
\]</span></p>
</section>
<section id="interpreting-eta-squared" class="level3" data-number="6.4.3">
<h3 data-number="6.4.3" class="anchored" data-anchor-id="interpreting-eta-squared"><span class="header-section-number">6.4.3</span> Interpreting eta-squared</h3>
<p>Cohen (1988) provided the following guidelines for interpreting eta-squared:</p>
<ul>
<li><span class="math inline">\(\eta^2\)</span> = .01 is a small effect</li>
<li><span class="math inline">\(\eta^2\)</span> = .06 is a medium effect</li>
<li><span class="math inline">\(\eta^2\)</span> = .14 is a large effect</li>
</ul>
<p>With these guidelines (which aren’t perfect), a <span class="math inline">\(\eta^2\)</span> of .778 is astronomically huge.</p>
<p>Alternatively, when it comes to eta-squared you can avoid using benchmarks entirely and interpret them as the amount of variance (as a percentage) explained in the DV by the IV, as described above.</p>
</section>
</section>
<section id="one-way-anova" class="level2" data-number="6.5">
<h2 data-number="6.5" class="anchored" data-anchor-id="one-way-anova"><span class="header-section-number">6.5</span> One-way ANOVA</h2>
<div style="background-color: #f5f5f5;  padding: 1.75rem;">
<p>In the previous section, we looked at how to compare differences between either two groups, or two points in time. But how do we compare more than that? The answer is the ANOVA (analysis of variance) - one of the most common general statistical models for hypothesis testing. If you do some statistical testing as part of your thesis, the ANOVA is likely going to be one of your most useful tools to have.</p>
</div>
<section id="the-basic-one-way-anova" class="level3" data-number="6.5.1">
<h3 data-number="6.5.1" class="anchored" data-anchor-id="the-basic-one-way-anova"><span class="header-section-number">6.5.1</span> The basic one-way ANOVA</h3>
<p>The between-groups one-way ANOVA is the most basic form of ANOVA, which aims to test differences between two or more groups. (Typically, ANOVAs are used when there are three or more groups, but can easily be used in situations where there are only two groups.)</p>
<p>We’ve briefly mentioned the general hypotheses for all ANOVAs, but here they are again:</p>
<ul>
<li><span class="math inline">\(H_0\)</span>: The means between groups are not significantly different. (i.e.&nbsp;<span class="math inline">\(\mu_1 = \mu_2 = ... \mu_k\)</span>)</li>
<li><span class="math inline">\(H_1\)</span>: The means between groups are significantly different. (i.e.<span class="math inline">\(\mu_1 \neq \mu_2 \neq ... \mu_k\)</span>)</li>
</ul>
</section>
<section id="example-data" class="level3" data-number="6.5.2">
<h3 data-number="6.5.2" class="anchored" data-anchor-id="example-data"><span class="header-section-number">6.5.2</span> Example data</h3>
<p>In the seminar, we talk about an example from Watts et al.&nbsp;(2003). Below is another simple example, comparing taste ratings across three different types of slices: caramel slices, vanilla slices and lemon slices. Participants were randomly allocated to taste one of the three slices blindfolded, and were then asked to verbally rate its taste on a scale from 1-10 (10 being super tasty).</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>w9_slices <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="fu">here</span>(<span class="st">"data"</span>, <span class="st">"week_9"</span>, <span class="st">"w9_slices.csv"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 63 Columns: 2
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (1): group
dbl (1): rating

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create factor</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>w9_slices<span class="sc">$</span>group <span class="ot">&lt;-</span> <span class="fu">factor</span>(w9_slices<span class="sc">$</span>group)</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(w9_slices)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 2
  group   rating
  &lt;fct&gt;    &lt;dbl&gt;
1 caramel      6
2 vanilla      8
3 lemon        4
4 caramel      6
5 vanilla      6
6 lemon        7</code></pre>
</div>
</div>
</section>
<section id="assumption-checks" class="level3" data-number="6.5.3">
<h3 data-number="6.5.3" class="anchored" data-anchor-id="assumption-checks"><span class="header-section-number">6.5.3</span> Assumption checks</h3>
<p>In R, to test assumptions we need to run the ANOVA <em>first</em>. This is because some assumptions rely on values that are calculated when the ANOVA is run. Other programs, such as Jamovi and SPSS, will hide this manual work and present the information to you automatically. This is not quite the case in R, but that’s ok!</p>
<p>The basic function for running an ANOVA in R is the <code>aov()</code> function, which takes a formula input (much like <code>t.test()</code>). Anything created using <code>aov()</code> should be assigned to a new variable so that we can use it later. This creates an <code>aov</code> object that will a) test our main effects and b) let us check some of our assumptions.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>w9_slices_aov <span class="ot">&lt;-</span> <span class="fu">aov</span>(rating <span class="sc">~</span> group, <span class="at">data =</span> w9_slices)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>There are four main assumptions for a basic ANOVA.</p>
<ul>
<li>Data must be independent of each other - in other words, one person’s response should not be influenced by another. This should come as a feature of good experimental design.</li>
<li>The residuals should be normally distributed. We can assess this using the same methods as <em>t</em>-tests: either a QQ plot or a normality test (e.g.&nbsp;Shapiro-Wilks). You can access the residuals from the <code>aov</code> object directly like this:</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>w9_slices_aov<span class="sc">$</span>residuals</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>This lets us do the SW test:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">shapiro.test</span>(w9_slices_aov<span class="sc">$</span>residuals)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Shapiro-Wilk normality test

data:  w9_slices_aov$residuals
W = 0.95117, p-value = 0.01409</code></pre>
</div>
</div>
<p>A SW test on this data suggests the assumption is violated (<em>W</em> =.951, <em>p</em> = .014), suggesting that the residuals are not normally distributed.</p>
<p>This is a bit of a problem in our dataset because our sample is relatively small. However - the ANOVA is fairly robust to violations of the normality assumption, meaning that non-normal residuals aren’t a major problem so long as a) you have a big enough sample size and b) the skew isn’t huge (or driven by outliers).</p>
<ul>
<li>The equality of variance (homoscedasticity) assumption.</li>
</ul>
<p>This means that the variances within each group are the same. We test this using Levene’s test, using the <code>levene_test()</code> function. Helpfully, <code>levene_test()</code> is flexible enough to work with either a formula <em>or</em> an <code>aov</code> object we have already fitted:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Either one of these will work</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>w9_slices <span class="sc">%&gt;%</span></span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">levene_test</span>(rating <span class="sc">~</span> group, <span class="at">center =</span> <span class="st">"mean"</span>)</span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a><span class="fu">levene_test</span>(w9_slices_aov, <span class="at">center =</span> <span class="st">"mean"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 4
    df1   df2 statistic     p
  &lt;int&gt; &lt;int&gt;     &lt;dbl&gt; &lt;dbl&gt;
1     2    60     0.721 0.491</code></pre>
</div>
</div>
<p>The assumption doesn’t appear to be violated (<em>F</em>(2, 60) = .721, <em>p</em> = .491). If it was, we might consider using a Welch’s ANOVA, which can be done with <code>welch_anova_test()</code> from <code>rstatix</code>.</p>
<p>For now though, we’ll press ahead.</p>
</section>
<section id="output" class="level3" data-number="6.5.4">
<h3 data-number="6.5.4" class="anchored" data-anchor-id="output"><span class="header-section-number">6.5.4</span> Output</h3>
<p>Here’s our main output from the ANOVA, generated using the <code>summary()</code> function. This is called an omnibus, because it is a general test of the hypotheses:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(w9_slices_aov)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>            Df Sum Sq Mean Sq F value  Pr(&gt;F)   
group        2  22.22  11.111   6.897 0.00201 **
Residuals   60  96.67   1.611                   
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>Our main results suggest that there is a significant difference between means (<em>F</em>(2, 60) = 6.90, <em>p</em> = .002).</p>
</section>
<section id="post-hoc-tests-1" class="level3" data-number="6.5.5">
<h3 data-number="6.5.5" class="anchored" data-anchor-id="post-hoc-tests-1"><span class="header-section-number">6.5.5</span> Post-hoc tests</h3>
<p>The output above told us that we could reject our basic null hypothesis - that there was no difference between means. However, remember that it doesn’t tell us where those differences are. To figure out where they are, we need to follow up that ANOVA with post-hoc tests.</p>
<p>To generate post-hocs, there are a couple of ways. Tukey tests can be calculated with <code>TukeyHSD()</code> or <code>emmeans()</code>:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">TukeyHSD</span>(w9_slices_aov)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Tukey multiple comparisons of means
    95% family-wise confidence level

Fit: aov(formula = rating ~ group, data = w9_slices)

$group
                      diff        lwr       upr     p adj
lemon-caramel   -0.4761905 -1.4175618 0.4651809 0.4486738
vanilla-caramel  0.9523810  0.0110096 1.8937523 0.0467882
vanilla-lemon    1.4285714  0.4872001 2.3699428 0.0015928</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">emmeans</span>(w9_slices_aov, <span class="sc">~</span> group) <span class="sc">%&gt;%</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pairs</span>(<span class="at">infer =</span> <span class="cn">TRUE</span>, <span class="at">adjust =</span> <span class="st">"tukey"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> contrast          estimate    SE df lower.CL upper.CL t.ratio p.value
 caramel - lemon      0.476 0.392 60   -0.465    1.418   1.216  0.4487
 caramel - vanilla   -0.952 0.392 60   -1.894   -0.011  -2.431  0.0468
 lemon - vanilla     -1.429 0.392 60   -2.370   -0.487  -3.647  0.0016

Confidence level used: 0.95 
Conf-level adjustment: tukey method for comparing a family of 3 estimates 
P value adjustment: tukey method for comparing a family of 3 estimates </code></pre>
</div>
</div>
<p>Here, you can see that we run a test for caramel vs lemon, caramel vs vanilla and lemon vs vanilla. For post-hocs in one-way ANOVAs, it is ok to stick to the Tukey-adjusted <em>p</em>-values. We can see that:</p>
<ul>
<li>There is no significant difference between ratings of caramel and lemon slices (mean difference, MD = .48; <em>p</em> = .449).</li>
<li>There is a (marginal) significant difference between caramel and vanilla slices; participants rated vanilla slices higher than caramel slices (MD = .95, <em>p</em> = .047).</li>
<li>There is a significant difference between lemon and vanilla slices, in that participants preferred vanilla slices (MD = 1.43, <em>p</em> = .002).</li>
</ul>
<p>To generate Bonferroni or Holm-corrected <em>p</em>-values, you need to use the <code>pairwise.t.test()</code> function:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pairwise.t.test</span>(<span class="at">x =</span> w9_slices<span class="sc">$</span>rating, <span class="at">g =</span> w9_slices<span class="sc">$</span>group, <span class="at">p.adjust.method =</span> <span class="st">"holm"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pairwise comparisons using t tests with pooled SD 

data:  w9_slices$rating and w9_slices$group 

        caramel lemon 
lemon   0.2289  -     
vanilla 0.0361  0.0017

P value adjustment method: holm </code></pre>
</div>
</div>
<p>In this case, you must provide <code>p.adjust.method</code> as an argument. By default, this function will use Holm corrections. Alternatively, just change your <code>emmeans()</code> call:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">emmeans</span>(w9_slices_aov, <span class="sc">~</span> group) <span class="sc">%&gt;%</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pairs</span>(<span class="at">infer =</span> <span class="cn">TRUE</span>, <span class="at">adjust =</span> <span class="st">"holm"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> contrast          estimate    SE df lower.CL upper.CL t.ratio p.value
 caramel - lemon      0.476 0.392 60   -0.489   1.4410   1.216  0.2289
 caramel - vanilla   -0.952 0.392 60   -1.917   0.0124  -2.431  0.0361
 lemon - vanilla     -1.429 0.392 60   -2.393  -0.4638  -3.647  0.0017

Confidence level used: 0.95 
Conf-level adjustment: bonferroni method for 3 estimates 
P value adjustment: holm method for 3 tests </code></pre>
</div>
</div>
<p>Here is how a write-up might look:</p>
<div style="background-color: #cce3c8;  padding: 1.75rem;">
<p>A one-way ANOVA was conducted to examine whether there were differences in preferences for types of slices. There was a significant large main effect of slice type (<em>F</em>(2, 60) = 6.90, <em>p</em> = .002, <span class="math inline">\(\eta^2\)</span> = .187). Post-hoc tests with Tukey HSD corrections showed that participants rated vanilla slices higher than caramel slices (mean difference, <em>MD</em> = .95, <em>p</em> = .047), as well as significantly higher than lemon slices (<em>MD</em> = 1.43, <em>p</em> = .002). However, there was no significant differencce between caramel and lemon slices (<em>p</em> = .449).</p>
</div>
</section>
</section>
<section id="one-way-repeated-measures-anova" class="level2" data-number="6.6">
<h2 data-number="6.6" class="anchored" data-anchor-id="one-way-repeated-measures-anova"><span class="header-section-number">6.6</span> One-way repeated measures ANOVA</h2>
<div style="background-color: #f5f5f5;  padding: 1.75rem;">
<p>The second form of ANOVA that we will cover in this module is the repeated measures ANOVA (sometimes abbreviated as RM-ANOVA). While it shares many features with the basic one-way ANOVA, the nature of repeated measures data introduces some key differences in the interpretation and calculation of this test.</p>
</div>
<section id="repeated-measures-anovas" class="level3" data-number="6.6.1">
<h3 data-number="6.6.1" class="anchored" data-anchor-id="repeated-measures-anovas"><span class="header-section-number">6.6.1</span> Repeated measures ANOVAs</h3>
<p>In principle, a repeated-measures ANOVA is very similar to the paired-samples <em>t</em>-test: both are repeated measures versions of their respective between-groups versions. So naturally, repeated-measures ANOVAs are used when we test one sample two or more times (again, like a regular ANOVA, it’s typically for 3+ times but can be used for two).</p>
<p>It shares many similarities with the basic one-way ANOVA, albeit with one additional step in calculation: because we now test the same sample repeatedly, we need to account for variance within subjects. We won’t go too into detail about how that’s calculated here, but essentially we split within-groups variance into subject variance and error/residual variance. This essentially adds an extra step to the ANOVA table.</p>
</section>
<section id="example-data-1" class="level3" data-number="6.6.2">
<h3 data-number="6.6.2" class="anchored" data-anchor-id="example-data-1"><span class="header-section-number">6.6.2</span> Example data</h3>
<p>In this example, we’ll use a dataset derived from <a href="https://journals.sagepub.com/doi/abs/10.1177/0305735605048012">McPherson (2005)</a>. This is a subset of data where children were scored on their ability to play songs from memory over three years - 1997 - 1999. We’re interested in seeing whether this change over time is significant - therefore, time (3 levels) is our independent variable, while playing from memory is our dependent variable.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>w9_memory <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="fu">here</span>(<span class="st">"data"</span>, <span class="st">"Week_9"</span>, <span class="st">"w9_playing_from_memory.csv"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 95 Columns: 4
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
dbl (4): Participant, PFM_97, PFM_98, PFM_99

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(w9_memory)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 4
  Participant PFM_97 PFM_98 PFM_99
        &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;
1           1     56    131    139
2           2     84    114    138
3           3    159    173    199
4           4    110    147    160
5           5    118    148    158
6           6    131    155    177</code></pre>
</div>
</div>
<p>For further analyses, we’ll shape this into long format:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>w9_memory_wide <span class="ot">&lt;-</span> w9_memory</span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a>w9_memory <span class="ot">&lt;-</span> w9_memory <span class="sc">%&gt;%</span></span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(</span>
<span id="cb39-5"><a href="#cb39-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">cols =</span> PFM_97<span class="sc">:</span>PFM_99,</span>
<span id="cb39-6"><a href="#cb39-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">names_to =</span> <span class="st">"time"</span>,</span>
<span id="cb39-7"><a href="#cb39-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">values_to =</span> <span class="st">"memory_score"</span></span>
<span id="cb39-8"><a href="#cb39-8" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="assumption-checks-1" class="level3" data-number="6.6.3">
<h3 data-number="6.6.3" class="anchored" data-anchor-id="assumption-checks-1"><span class="header-section-number">6.6.3</span> Assumption checks</h3>
<p>There are two main assumptions for a repeated-measures ANOVA. Note that while the independence assumption as we know it doesn’t apply here (by definition, repeated data is dependent), good experimental design should still aim to ensure that participants are independent of each other.</p>
<ul>
<li>The residuals should be normally distributed.</li>
</ul>
<p>Our usual tests apply here too. Below is a QQ plot, which might suggest that our residuals aren’t normally distributed. (Use the data and perform a SW test on it to see what happens!)</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">aov</span>(memory_score <span class="sc">~</span> time, <span class="at">data =</span> w9_memory) <span class="sc">%&gt;%</span></span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>  broom<span class="sc">::</span><span class="fu">augment</span>() <span class="sc">%&gt;%</span></span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">sample =</span> .std.resid)) <span class="sc">+</span></span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_qq</span>() <span class="sc">+</span></span>
<span id="cb40-5"><a href="#cb40-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_qq_line</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: The `augment()` method for objects of class `aov` is not maintained by the broom team, and is only supported through the `lm` tidier method. Please be cautious in interpreting and reporting broom output.

This warning is displayed once per session.</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="06-anovas_files/figure-html/unnamed-chunk-34-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<ul>
<li>The sphericity assumption. Sphericity is assumed if, the variances of the differences between each level of the IV are equal. Think of it as a form of the equality of variances assumption, where we assumed that the variances within groups were equal. The sphericity assumption applies to the differences between T1 and T2, then T2 and T3… etc etc.</li>
</ul>
<p>Note that sphericity only applies when you have at least 3 levels of your IV (i.e.&nbsp;3 timepoints). We can formally test it using Mauchly’s test of sphericity. If sphericity is violated, it means that our degrees of freedom are too high for the data, which inflates the Type I error rate.</p>
<p>What next? We need to apply a correction to the omnibus ANOVA, which will alter the <em>p</em>-value. There are two on offer: Greenhouse-Geisser and Huynh-Feldt corrections. To help decide which one to use, R also calculates a value called epsilon (<span class="math inline">\(\epsilon\)</span>). Epsilon, in short, is a measure of sphericity; if sphericity is assumed, <span class="math inline">\(\epsilon\)</span> = 1. If <span class="math inline">\(\epsilon\)</span> is below 1, sphericity is violated; the smaller it is, the greater the violation and therefore the greater the correction needs to be. Therefore, these corrections alter the degrees of freedom for each test to account for this higher error rate.</p>
<p>(Mathematical note; the corrected dfs are calculated by multiplying the original dfs by <span class="math inline">\(\epsilon\)</span>. So e.g.&nbsp;if your original df is 10 and <span class="math inline">\(\epsilon\)</span> = 0.9, your new corrected df will be 9.)</p>
<p>Broadly:</p>
<ul>
<li>If epsilon (<span class="math inline">\(\epsilon\)</span>) &gt; .75, use the Huynh-Feldt correction.</li>
<li>If epsilon (<span class="math inline">\(\epsilon\)</span>) &lt; .75, use the Greenhouse-Geisser correction.</li>
</ul>
<p>In R, most main packages will test the sphericity assumption along with the main ANOVA, so we will see this below.</p>
</section>
<section id="anova-output" class="level3" data-number="6.6.4">
<h3 data-number="6.6.4" class="anchored" data-anchor-id="anova-output"><span class="header-section-number">6.6.4</span> ANOVA output</h3>
<p>Repeated measures ANOVAs in R are surprisingly <em>not</em> trivial to conduct, to the point where even adapting the Jamovi version of this analysis was a genuine challenge. To some extent this probably reflects the differences in approach between point-and-click software compared to actually having to code the ANOVA model: the former is easy but you perhaps make certain assumptions about what’s going on along the way.</p>
<p>For that reason, now is a good time to introduce the <code>afex</code> package, which stands for “analysis of factorial experiments”. The <code>aov_ez()</code> function will let us specify a repeated measures ANOVA in a very easy way. See below for an alternative using <code>rstatix</code>, although this is less flexible than the <code>afex</code> version.</p>
<p>At a minimum, you must give the following arguments to <code>aov_ez()</code>:</p>
<ul>
<li><code>id</code>: The name of the column that identifies each participant</li>
<li><code>dv</code>: The dependent variable/outcome</li>
<li><code>data</code>: The name of the dataset</li>
<li><code>within</code>: The name of the within-subjects IV/predictor</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(afex)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: lme4</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: Matrix</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'Matrix'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:tidyr':

    expand, pack, unpack</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Registered S3 method overwritten by 'lme4':
  method           from
  na.action.merMod car </code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>************
Welcome to afex. For support visit: http://afex.singmann.science/</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>- Functions for ANOVAs: aov_car(), aov_ez(), and aov_4()
- Methods for calculating p-values with mixed(): 'S', 'KR', 'LRT', and 'PB'
- 'afex_aov' and 'mixed' objects can be passed to emmeans() for follow-up tests
- Get and set global package options with: afex_options()
- Set sum-to-zero contrasts globally: set_sum_contrasts()
- For example analyses see: browseVignettes("afex")
************</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'afex'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:lme4':

    lmer</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a>w9_memory_aov <span class="ot">&lt;-</span> <span class="fu">aov_ez</span>(</span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">id =</span> <span class="st">"Participant"</span>,</span>
<span id="cb52-3"><a href="#cb52-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">dv =</span> <span class="st">"memory_score"</span>,</span>
<span id="cb52-4"><a href="#cb52-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> w9_memory,</span>
<span id="cb52-5"><a href="#cb52-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">within =</span> <span class="st">"time"</span>,</span>
<span id="cb52-6"><a href="#cb52-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">type =</span> <span class="dv">3</span>,</span>
<span id="cb52-7"><a href="#cb52-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">anova_table =</span> <span class="fu">list</span>(</span>
<span id="cb52-8"><a href="#cb52-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">correction =</span> <span class="st">"HF"</span>,</span>
<span id="cb52-9"><a href="#cb52-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">es =</span> <span class="st">"pes"</span></span>
<span id="cb52-10"><a href="#cb52-10" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb52-11"><a href="#cb52-11" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Also worth noting is the <code>anova_table</code> argument, which specifies options for the main output. This argument takes a <code>list()</code> as the argument, and we can set multiple options within this list. Here, we have set two:</p>
<ul>
<li><code>correction = "HF"</code> specifies Huynh-Felt corrections. We can also ask for Greenhouse-Geisser corrections using <code>correction = "GG"</code>.</li>
<li><code>es = "pes"</code> specifies partial eta-squared for effect size. This is ok for a one-way ANOVA; recall that for a one-way setting, normal and partial eta-squared are the same.</li>
</ul>
<p>Now that we’ve built our ANOVA model we can ask for the output like so. This will also print out the sphericity test.</p>
<p>Here’s our overall output from the ANOVA. It looks (and reads) pretty much the same as our previous example, albeit with some minor differences.</p>
<p>To see the full output, including the sphericity test, call <code>summary()</code> on your ANOVA object:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(w9_memory_aov)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Univariate Type III Repeated-Measures ANOVA Assuming Sphericity

             Sum Sq num Df Error SS den Df F value    Pr(&gt;F)    
(Intercept) 3490869      1   259027     94 1266.83 &lt; 2.2e-16 ***
time          98948      2    70130    188  132.63 &lt; 2.2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1


Mauchly Tests for Sphericity

     Test statistic  p-value
time        0.93912 0.053894


Greenhouse-Geisser and Huynh-Feldt Corrections
 for Departure from Sphericity

      GG eps Pr(&gt;F[GG])    
time 0.94261  &lt; 2.2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

        HF eps   Pr(&gt;F[HF])
time 0.9612827 2.447568e-35</code></pre>
</div>
</div>
<p>Here, our <em>p</em>-value for Mauchly’s test is almost significant (<em>p</em> = .054); rather than going by a strict arbitrary cutoff, let’s assume that it has been violated (both for teaching and for methodological purposes). Here, our epsilon value is high (~.95), so let’s apply the Hyunh-Feldt correction. The associated epsilon value is <span class="math inline">\(\epsilon = .943\)</span>; when reporting the repeated measures ANOVA we need to look at the rows corresponding to the Huynh-Feldt correction.</p>
<p><code>afex</code> will print out the <em>corrected</em> version of the test if you just print the object without using <code>summary()</code>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a>w9_memory_aov</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Anova Table (Type 3 tests)

Response: memory_score
  Effect           df    MSE          F  pes p.value
1   time 1.92, 180.72 388.06 132.63 *** .585   &lt;.001
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '+' 0.1 ' ' 1

Sphericity correction method: HF </code></pre>
</div>
</div>
<p>Thus, with the corrected output we can see our effect of time is significant (<em>F</em>(1.92, 180.72) = 132.63, <em>p</em> &lt; .001).</p>
<p>A benefit of doing a repeated-measures ANOVA this way is that this model is compatible with the <code>effectsize</code> functions, including <code>eta_squared()</code>:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="fu">eta_squared</span>(w9_memory_aov, <span class="at">alternative =</span> <span class="st">"two.sided"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># Effect Size for ANOVA (Type III)

Parameter | Eta2 (partial) |       95% CI
-----------------------------------------
time      |           0.59 | [0.50, 0.65]</code></pre>
</div>
</div>
</section>
<section id="post-hoc-tests-2" class="level3" data-number="6.6.5">
<h3 data-number="6.6.5" class="anchored" data-anchor-id="post-hoc-tests-2"><span class="header-section-number">6.6.5</span> Post-hoc tests</h3>
<p>As per usual, we follow up a significant overall ANOVA with a series of post-hoc comparisons:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="fu">emmeans</span>(w9_memory_aov, <span class="sc">~</span> time) <span class="sc">%&gt;%</span></span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pairs</span>(<span class="at">infer =</span> <span class="cn">TRUE</span>, <span class="at">adjust =</span> <span class="st">"holm"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> contrast        estimate   SE df lower.CL upper.CL t.ratio p.value
 PFM_97 - PFM_98    -29.6 2.82 94    -36.5   -22.74 -10.501 &lt;0.0001
 PFM_97 - PFM_99    -44.9 3.08 94    -52.4   -37.38 -14.577 &lt;0.0001
 PFM_98 - PFM_99    -15.3 2.48 94    -21.3    -9.24  -6.170 &lt;0.0001

Confidence level used: 0.95 
Conf-level adjustment: bonferroni method for 3 estimates 
P value adjustment: holm method for 3 tests </code></pre>
</div>
</div>
<p>As an alternative, we can use <code>pairwise.t.test()</code>. Note this time we set <code>paired = TRUE</code>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pairwise.t.test</span>(w9_memory<span class="sc">$</span>memory_score, w9_memory<span class="sc">$</span>time, <span class="at">paired =</span> <span class="cn">TRUE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pairwise comparisons using paired t tests 

data:  w9_memory$memory_score and w9_memory$time 

       PFM_97  PFM_98 
PFM_98 &lt; 2e-16 -      
PFM_99 &lt; 2e-16 1.7e-08

P value adjustment method: holm </code></pre>
</div>
</div>
<p>From this, we can see that all three means are significantly different from each other (<em>p</em> &lt; .001, for brevity’s sake). Scores increased year on year, i.e.&nbsp;1997 &lt; 1998 &lt; 1999.</p>
<div style="background-color: #cce3c8;  padding: 1.75rem;">
<p>A one-way repeated measures ANOVA was conducted to examine whether scores for playing songs from memory changed over three years. We applied Huynh-Feldt corrections to account for non-sphericity. There was a significant large effect of year on performance scores (<em>F</em>(1.92, 180.72) = 132.63, <em>p</em> &lt; .001, <span class="math inline">\(\eta^2\)</span> = .231). Post-hoc tests with Tukey HSD corrections showed that participants scored higher in 1998 than in 1997 (mean difference, <em>MD</em> = 29.61, <em>p</em> &lt; .001). Participants also scored higher in 1999 compared to 1998 (<em>MD</em> = 15.27, <em>p</em> &lt; .001) and 1997 (<em>MD</em> = 44.88, <em>p</em> &lt; .001).</p>
</div>
</section>
<section id="alternative-using-rstatix" class="level3" data-number="6.6.6">
<h3 data-number="6.6.6" class="anchored" data-anchor-id="alternative-using-rstatix"><span class="header-section-number">6.6.6</span> Alternative using <code>rstatix</code></h3>
<p>As mentioned above, repeated measures ANOVAs in R are not trivial at all. The solution using <code>rstatix</code> above is good, although it is not fully ideal.</p>
<p>Below is an alternative way of running a repeated measures ANOVA, this time using the <code>rstatix</code> package. It even uses similar arguments to the <code>afex</code> version above.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a>w9_memory_aov2 <span class="ot">&lt;-</span> w9_memory <span class="sc">%&gt;%</span></span>
<span id="cb63-2"><a href="#cb63-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">anova_test</span>(<span class="at">dv =</span> memory_score, <span class="at">wid =</span> Participant, <span class="at">within =</span> time) </span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a>w9_memory_aov2</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>ANOVA Table (type III tests)

$ANOVA
  Effect DFn DFd       F        p p&lt;.05   ges
1   time   2 188 132.625 1.19e-36     * 0.231

$`Mauchly's Test for Sphericity`
  Effect     W     p p&lt;.05
1   time 0.939 0.054      

$`Sphericity Corrections`
  Effect   GGe       DF[GG]    p[GG] p[GG]&lt;.05   HFe       DF[HF]    p[HF]
1   time 0.943 1.89, 177.21 1.05e-34         * 0.961 1.92, 180.72 2.45e-35
  p[HF]&lt;.05
1         *</code></pre>
</div>
</div>
<p>The two columns to look for are the ones labelled <code>DF[HF]</code> - this gives the adjusted degrees of freedom with the Huynh-Feldt corrections (<code>DF[GG]</code> would give Greenhouse-Geisser dfs) - and <code>p[HF]</code>, which gives the adjusted <em>p</em>-value.</p>
<p>Note that the <code>rstatix</code> version is not compatible with either <code>eta_squared()</code> (from the <code>effectsize</code> package) or <code>emmeans</code>. If you want post-hocs, you will need to use the <code>pairwise.t.test()</code> function or its <code>rstatix</code> equivalent. However, this does mean that it is not possible to do Tukey adjustments.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a>w9_memory <span class="sc">%&gt;%</span></span>
<span id="cb66-2"><a href="#cb66-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pairwise_t_test</span>(memory_score <span class="sc">~</span> time, <span class="at">paired =</span> <span class="cn">TRUE</span>, <span class="at">p.adjust.method =</span> <span class="st">"holm"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 10
  .y.   group1 group2    n1    n2 statistic    df        p    p.adj p.adj.signif
* &lt;chr&gt; &lt;chr&gt;  &lt;chr&gt;  &lt;int&gt; &lt;int&gt;     &lt;dbl&gt; &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt; &lt;chr&gt;       
1 memo… PFM_97 PFM_98    95    95    -10.5     94 1.59e-17 3.18e-17 ****        
2 memo… PFM_97 PFM_99    95    95    -14.6     94 7.35e-26 2.21e-25 ****        
3 memo… PFM_98 PFM_99    95    95     -6.17    94 1.71e- 8 1.71e- 8 ****        </code></pre>
</div>
</div>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./05-ttests.html" class="pagination-link" aria-label="t-tests">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">t-tests</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./07-regressions.html" class="pagination-link" aria-label="Linear relationships">
        <span class="nav-page-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Linear relationships</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>Copyright 2026, Daniel Yeom</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
      <ul class="footer-items list-unstyled">
    <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/danyeom">
      <i class="bi bi-github" role="img">
</i> 
    </a>
  </li>  
</ul>
    </div>
  </div>
</footer>




</body></html>