<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.36">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>9&nbsp; Regression continued – Research Process for Music Psychologists</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./10-logistic.html" rel="next">
<link href="./08-factorial-anovas.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-845c23b38eaddc0f92fda52bfe77a8c8.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-9e3e5b9121e68b3f077afb32f2c64d95.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./08-factorial-anovas.html">Part III: Advanced methods</a></li><li class="breadcrumb-item"><a href="./09-regressions-2.html"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Regression continued</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Research Process for Music Psychologists</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Part I: Introduction</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">A very brief introduction to R</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-descriptives.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Descriptive statistics</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-inferential.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Inferential statistics</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Part II: Basic inferential tests</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-chisquares.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Chi-squares</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-ttests.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">t-tests</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06-anovas.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">ANOVAs</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07-regressions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Linear relationships</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Part III: Advanced methods</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08-factorial-anovas.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Factorial ANOVAs</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./09-regressions-2.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Regression continued</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./10-logistic.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Logistic regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./11-efa.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Exploratory factor analysis</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./12-medmod.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Mediation and Moderation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./13-nonpara.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Non-parametric tests</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./appendix.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Appendix</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#ancovas" id="toc-ancovas" class="nav-link active" data-scroll-target="#ancovas"><span class="header-section-number">9.1</span> ANCOVAs</a>
  <ul class="collapse">
  <li><a href="#introduction" id="toc-introduction" class="nav-link" data-scroll-target="#introduction"><span class="header-section-number">9.1.1</span> Introduction</a></li>
  <li><a href="#example" id="toc-example" class="nav-link" data-scroll-target="#example"><span class="header-section-number">9.1.2</span> Example</a></li>
  <li><a href="#one-way-ancova" id="toc-one-way-ancova" class="nav-link" data-scroll-target="#one-way-ancova"><span class="header-section-number">9.1.3</span> One-way ANCOVA</a></li>
  <li><a href="#assumptions" id="toc-assumptions" class="nav-link" data-scroll-target="#assumptions"><span class="header-section-number">9.1.4</span> Assumptions</a></li>
  <li><a href="#linearity-of-the-covariate" id="toc-linearity-of-the-covariate" class="nav-link" data-scroll-target="#linearity-of-the-covariate"><span class="header-section-number">9.1.5</span> Linearity of the covariate</a></li>
  </ul></li>
  <li><a href="#hierarchical-regression" id="toc-hierarchical-regression" class="nav-link" data-scroll-target="#hierarchical-regression"><span class="header-section-number">9.2</span> Hierarchical regression</a>
  <ul class="collapse">
  <li><a href="#example-1" id="toc-example-1" class="nav-link" data-scroll-target="#example-1"><span class="header-section-number">9.2.1</span> Example</a></li>
  <li><a href="#building-blocks-and-output" id="toc-building-blocks-and-output" class="nav-link" data-scroll-target="#building-blocks-and-output"><span class="header-section-number">9.2.2</span> Building blocks and output</a></li>
  </ul></li>
  <li><a href="#comparing-models" id="toc-comparing-models" class="nav-link" data-scroll-target="#comparing-models"><span class="header-section-number">9.3</span> Comparing models</a>
  <ul class="collapse">
  <li><a href="#comparing-r2" id="toc-comparing-r2" class="nav-link" data-scroll-target="#comparing-r2"><span class="header-section-number">9.3.1</span> Comparing <span class="math inline">\(R^2\)</span></a></li>
  <li><a href="#nested-model-tests" id="toc-nested-model-tests" class="nav-link" data-scroll-target="#nested-model-tests"><span class="header-section-number">9.3.2</span> Nested model tests</a></li>
  <li><a href="#fit-indices" id="toc-fit-indices" class="nav-link" data-scroll-target="#fit-indices"><span class="header-section-number">9.3.3</span> Fit indices</a></li>
  </ul></li>
  <li><a href="#outliers" id="toc-outliers" class="nav-link" data-scroll-target="#outliers"><span class="header-section-number">9.4</span> Outliers</a>
  <ul class="collapse">
  <li><a href="#cooks-distance" id="toc-cooks-distance" class="nav-link" data-scroll-target="#cooks-distance"><span class="header-section-number">9.4.1</span> Cook’s distance</a></li>
  <li><a href="#mahalanobis-distance-d2" id="toc-mahalanobis-distance-d2" class="nav-link" data-scroll-target="#mahalanobis-distance-d2"><span class="header-section-number">9.4.2</span> Mahalanobis’ distance, <span class="math inline">\(D^2\)</span></a></li>
  <li><a href="#what-happens-if-there-is-an-outlier" id="toc-what-happens-if-there-is-an-outlier" class="nav-link" data-scroll-target="#what-happens-if-there-is-an-outlier"><span class="header-section-number">9.4.3</span> What happens if there is an outlier?</a></li>
  </ul></li>
  <li><a href="#partial-correlations" id="toc-partial-correlations" class="nav-link" data-scroll-target="#partial-correlations"><span class="header-section-number">9.5</span> Partial correlations</a>
  <ul class="collapse">
  <li><a href="#introduction-1" id="toc-introduction-1" class="nav-link" data-scroll-target="#introduction-1"><span class="header-section-number">9.5.1</span> Introduction</a></li>
  <li><a href="#partial-correlations-1" id="toc-partial-correlations-1" class="nav-link" data-scroll-target="#partial-correlations-1"><span class="header-section-number">9.5.2</span> Partial correlations</a></li>
  </ul></li>
  <li><a href="#semipartial-correlations" id="toc-semipartial-correlations" class="nav-link" data-scroll-target="#semipartial-correlations"><span class="header-section-number">9.6</span> Semipartial correlations</a>
  <ul class="collapse">
  <li><a href="#semipartial-correlations-sr" id="toc-semipartial-correlations-sr" class="nav-link" data-scroll-target="#semipartial-correlations-sr"><span class="header-section-number">9.6.1</span> Semipartial correlations (<em>sr</em>)</a></li>
  <li><a href="#example-2" id="toc-example-2" class="nav-link" data-scroll-target="#example-2"><span class="header-section-number">9.6.2</span> Example</a></li>
  <li><a href="#calculating-all-sr2-values" id="toc-calculating-all-sr2-values" class="nav-link" data-scroll-target="#calculating-all-sr2-values"><span class="header-section-number">9.6.3</span> Calculating all <span class="math inline">\(sr^2\)</span> values</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./08-factorial-anovas.html">Part III: Advanced methods</a></li><li class="breadcrumb-item"><a href="./09-regressions-2.html"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Regression continued</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Regression continued</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>This section deals with some more advanced topics in ANOVAs and regression. It serves as a continuation to the first chapter on regression, and in particular focuses on multiple regressions. This chapter will cover the following:</p>
<ul>
<li>ANCOVA</li>
<li>Hierarchical regressions</li>
<li>Model selection</li>
<li>Identifying and handling outliers</li>
</ul>
<p>This module won’t cover continuous interactions because they are often considered under the topic of moderation - for which there will be a separate module.</p>
<p>Recall that the basic multiple regression looks something like this:</p>
<p><span class="math display">\[
y = \beta_0 + \beta_1x_1 +\beta_2x_2 + \epsilon_i
\]</span> As a reminder, the coefficients in this formula correspond to the following:</p>
<ul>
<li><span class="math inline">\(\beta_1\)</span> is the coefficient for predictor <span class="math inline">\(x_1\)</span>; i.e.&nbsp;as <span class="math inline">\(x_1\)</span> increases by 1 unit, <span class="math inline">\(\hat y\)</span> (the predicted y value) increases by <span class="math inline">\(\beta_1\)</span> units, <em>assuming</em> <span class="math inline">\(x_2\)</span> does not change</li>
<li><span class="math inline">\(\beta_2\)</span> is the coefficient for predictor <span class="math inline">\(x_2\)</span>, and describes how <span class="math inline">\(\hat y\)</span> changes assuming <span class="math inline">\(x_1\)</span> does not change</li>
<li><span class="math inline">\(\epsilon_i\)</span> is the error term, which we assume is normally distributed</li>
</ul>
<p>We can expand this formula out to include <span class="math inline">\(n\)</span> predictors, as follows:</p>
<p><span class="math display">\[
y = \beta_0 + \beta_1x_1 +\beta_2x_2 + ... \beta_nx_n + \epsilon_i
\]</span></p>
<section id="ancovas" class="level2" data-number="9.1">
<h2 data-number="9.1" class="anchored" data-anchor-id="ancovas"><span class="header-section-number">9.1</span> ANCOVAs</h2>
<section id="introduction" class="level3" data-number="9.1.1">
<h3 data-number="9.1.1" class="anchored" data-anchor-id="introduction"><span class="header-section-number">9.1.1</span> Introduction</h3>
<p>ANCOVA stands for Analysis of <strong>Co-</strong>variance. Its basic definition is that it is an ANOVA, but with the inclusion of a covariate (or a variable we need to control for). The basic idea is that we are performing an ANOVA between our predictors and outcomes after adjusting our predictors (our model) by another variable.</p>
<p>Just like the ANOVA, ANCOVA is a fairly generic term that can refer to a multitude of analyses. In this book we’ll stick with ANOVAs relating to between-subjects predictors only.</p>
</section>
<section id="example" class="level3" data-number="9.1.2">
<h3 data-number="9.1.2" class="anchored" data-anchor-id="example"><span class="header-section-number">9.1.2</span> Example</h3>
<p>The following data comes from Plaster (1989). The dataset is described as below:</p>
<blockquote class="blockquote">
<p>Male participants were shown a picture of one of three young women. Pilot work had indicated that the one woman was beautiful, another of average physical attractiveness, and the third unattractive. Participants rated the woman they saw on each of twelve attributes. These measures were used to check on the manipulation by the photo. Then the participants were told that the person in the photo had committed a Crime, and asked to rate the seriousness of the crime and recommend a prison sentence, in Years.</p>
</blockquote>
<p>Our main questions are:</p>
<ol type="1">
<li>Does the perceived attractiveness of the “defendant” (the women in the photo) influence the number of years the mock juror (the participant) sentence them for?</li>
<li>How does this relationship change after controlling for the perceived seriousness of the crime?</li>
</ol>
<p>Our dataset, <code>jury_data</code>, contains the following variables:</p>
<ul>
<li>Attr: The perceived attractiveness of the defendant (Beautiful, Average, Unattractive)</li>
<li>Crime: The crime that was commited by the defendant (Burglary, Swindle)</li>
<li>Serious: The perceived seriousness of the crime from 1-10</li>
<li>Years: The number of years the participant sentenced the defendant for</li>
</ul>
</section>
<section id="one-way-ancova" class="level3" data-number="9.1.3">
<h3 data-number="9.1.3" class="anchored" data-anchor-id="one-way-ancova"><span class="header-section-number">9.1.3</span> One-way ANCOVA</h3>
<p>To start us off, let’s begin with a simple one-way ANOVA between attractiveness and years. We can see this below.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>jury_data <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="fu">here</span>(<span class="st">"data"</span>, <span class="st">"regression_2"</span>, <span class="st">"anova_mockjury.csv"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>jury_aov <span class="ot">&lt;-</span> <span class="fu">aov</span>(Years <span class="sc">~</span> Attr, <span class="at">data =</span> jury_data)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(jury_aov)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>             Df Sum Sq Mean Sq F value Pr(&gt;F)  
Attr          2   70.9   35.47    2.77  0.067 .
Residuals   111 1421.3   12.80                 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">eta_squared</span>(jury_aov, <span class="at">alternative =</span> <span class="st">"two.sided"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>For one-way between subjects designs, partial eta squared is equivalent
  to eta squared. Returning eta squared.</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code># Effect Size for ANOVA

Parameter | Eta2 |       95% CI
-------------------------------
Attr      | 0.05 | [0.00, 0.14]</code></pre>
</div>
</div>
<p>From this we can infer that the effect of attractiveness is not significant (<em>F</em>(2, 111) = 2.77, <em>p</em> = .067, <span class="math inline">\(\eta^2\)</span> = .05, 95% CI = [0, .14]). In other words, perceived attractiveness does not appear to relate to the years of sentencing.</p>
<p>Let’s now add the covariate <code>Serious</code> in. To do this in R, we simply add in the predictor to the <code>aov</code> model just like we would with adding a second predictor in a multiple regression - by specifying <code>IV + covariate</code> within the relevant function. See below for two ways of running an ANCOVA:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># One way using car::Anova - this is useful for getting the correct eta squared confidence intervals</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a><span class="fu">options</span>(<span class="at">contrasts =</span> <span class="fu">c</span>(<span class="st">"contr.helmert"</span>, <span class="st">"contr.poly"</span>))</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>jury_acov <span class="ot">&lt;-</span> <span class="fu">aov</span>(Years <span class="sc">~</span> Attr <span class="sc">+</span> Serious, <span class="at">data =</span> jury_data)</span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>jury_acov_sum <span class="ot">&lt;-</span> car<span class="sc">::</span><span class="fu">Anova</span>(jury_acov, <span class="at">type =</span> <span class="dv">3</span>)</span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>jury_acov_sum</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Anova Table (Type III tests)

Response: Years
             Sum Sq  Df F value    Pr(&gt;F)    
(Intercept)    4.56   1  0.4819   0.48902    
Attr          73.26   2  3.8735   0.02368 *  
Serious      381.15   1 40.3068 4.998e-09 ***
Residuals   1040.17 110                      
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">eta_squared</span>(jury_acov_sum, <span class="at">alternative =</span> <span class="st">"two.sided"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># Effect Size for ANOVA (Type III)

Parameter | Eta2 (partial) |       95% CI
-----------------------------------------
Attr      |           0.07 | [0.00, 0.16]
Serious   |           0.27 | [0.14, 0.39]</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Another way using rstatix</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>jury_data <span class="sc">%&gt;%</span></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">anova_test</span>(Years <span class="sc">~</span> Attr <span class="sc">+</span> Serious, <span class="at">effect.size =</span> <span class="st">"pes"</span>, <span class="at">type =</span> <span class="dv">3</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>ANOVA Table (type III tests)

   Effect DFn DFd      F       p p&lt;.05   pes
1    Attr   2 110  3.873 2.4e-02     * 0.066
2 Serious   1 110 40.307 5.0e-09     * 0.268</code></pre>
</div>
</div>
<p>What do we see? Well, the main effect of attractiveness is now significant (<em>F</em>(2, 110) = 3.87, <em>p</em> = .024, <span class="math inline">\(\eta^2_p\)</span> = .07, 95% CI = [0, .16]). The effect of the covariate is also significant (<em>F</em>(1, 110) = 40.31, <em>p</em> &lt; .001, <span class="math inline">\(\eta^2_p\)</span> = .27, 95% CI = [.14, .39]).</p>
<p>What’s actually going on here? Well, the first model showed us that by itself, attractiveness was not a significant part of the model. However, once we factored in the effect of Seriousness (and more importantly, controlled for it) we saw that Attractive <em>did</em> in fact relate to the sentence length. Unsurprisingly, the seriousness of the crime also predicted sentence length.</p>
</section>
<section id="assumptions" class="level3" data-number="9.1.4">
<h3 data-number="9.1.4" class="anchored" data-anchor-id="assumptions"><span class="header-section-number">9.1.4</span> Assumptions</h3>
<p>By and large, the assumptions required for an ANCOVA are the same as that of a regular ANOVA. However, there are two new ones in bold below:</p>
<ul>
<li>Normality of residuals</li>
<li>Homogeneity of variances</li>
<li><strong>Linearity of the covariate</strong></li>
<li><strong>Homogeneity of regression slopes</strong></li>
</ul>
<p>Let’s check each of these below.</p>
<p>First, the normality of residuals can simply be tested as in the usual way. Our residuals are not normally distributed in this model (<em>W</em> = .97, <em>p</em> = .006).</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">shapiro.test</span>(jury_acov<span class="sc">$</span>residuals)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Shapiro-Wilk normality test

data:  jury_acov$residuals
W = 0.96616, p-value = 0.005529</code></pre>
</div>
</div>
<p>The homoegeneity of variance assumption is also largely tested in the same way. Our homogeneity of variance assumption also isn’t met (<em>F</em>(2, 111) = 5.68, <em>p</em> = .004)…</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>jury_data <span class="sc">%&gt;%</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">levene_test</span>(Years <span class="sc">~</span> Attr, <span class="at">center =</span> <span class="st">"mean"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in leveneTest.default(y = y, group = group, ...): group coerced to
factor.</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 4
    df1   df2 statistic       p
  &lt;int&gt; &lt;int&gt;     &lt;dbl&gt;   &lt;dbl&gt;
1     2   111      5.68 0.00446</code></pre>
</div>
</div>
</section>
<section id="linearity-of-the-covariate" class="level3" data-number="9.1.5">
<h3 data-number="9.1.5" class="anchored" data-anchor-id="linearity-of-the-covariate"><span class="header-section-number">9.1.5</span> Linearity of the covariate</h3>
<p>A third assumption tests whether the covariate is linearly related to the DV. This assumption is essentially similar to the linearity assumption in a regression model - because we are still dealing with linear models, our covariates must also be linearly related to our outcome.</p>
<p>This is simple enough to test just by visualising the relationship. In general, this assumption appears to hold - it looks like there’s a vague linear relationship in there.</p>
<p>(Note that due to the data being in integers - i.e.&nbsp;whole numbers - I’ve used <code>geom_jitter()</code> in place of <code>geom_point()</code> to help visualise this a bit better.)</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>jury_data <span class="sc">%&gt;%</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">aes</span>(<span class="at">x =</span> Serious, <span class="at">y =</span> Years)</span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span> </span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_jitter</span>() <span class="sc">+</span> </span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Perceived seriousness of crime"</span>, <span class="at">y =</span> <span class="st">"Sentence length (Years)"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="09-regressions-2_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Finally, the <strong>homogeneity of regression slopes</strong> assumption specifies that for each group, the slope of the relationship between the covariate and the dependent variable are the same. To test this, we need to run an ANOVA that allows for an interaction between the predictor and covariate.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>jury_data <span class="sc">%&gt;%</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">anova_test</span>(Years <span class="sc">~</span> Attr <span class="sc">*</span> Serious, <span class="at">effect.size =</span> <span class="st">"pes"</span>, <span class="at">type =</span> <span class="dv">3</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>ANOVA Table (type III tests)

        Effect DFn DFd      F        p p&lt;.05   pes
1         Attr   2 108  0.951 3.90e-01       0.017
2      Serious   1 108 42.794 2.09e-09     * 0.284
3 Attr:Serious   2 108  3.622 3.00e-02     * 0.063</code></pre>
</div>
</div>
<p>Uh oh - this isn’t good. A significant interaction suggests that the slope of the relationship between <code>Serious</code> and <code>Years</code> differs for each level of attractiveness, as indicated by the significant interaction effect (<em>p</em> = .03). We can see as much if we fit separate regression lines to the scatterplot above:</p>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>jury_data <span class="sc">%&gt;%</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">aes</span>(<span class="at">x =</span> Serious, <span class="at">y =</span> Years, <span class="at">colour =</span> Attr)</span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span> </span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_jitter</span>() <span class="sc">+</span> </span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Perceived seriousness of crime"</span>, <span class="at">y =</span> <span class="st">"Sentence length (Years)"</span>) <span class="sc">+</span></span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> lm, <span class="at">se =</span> <span class="cn">FALSE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="09-regressions-2_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>As we can clearly see, the slopes are not identical for each group. In particular, the Unattractive group has a much stronger slope between seriousness and sentence length (indicating that unattractive people basically have it harder if they’re perceived to have committed more serious crimes).</p>
<p>Overall, given that many of our assumptions are not met - particularly the important one of homogeneity of regression slopes - this indicates that an ANCOVA isn’t a suitable model for our data. What would we do in this instance, then? We’d probably model a regression that allows for the interaction between attractiveness and seriousness.</p>
<p>A final note on ANCOVAs: naturally, we can extend an ANCOVA model to have multiple predictors <em>and</em> multiple covariates. In this instance, we would need to model multi-way interactions to test all of our effects and assumptions. Below is a lightly annotated example of a two-way ANCOVA using attractiveness and type of crime as predictors, seriousness as a covariate and sentence length as an outcome.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Build two way ANCOVA</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>jury_twoway_acov <span class="ot">&lt;-</span> <span class="fu">aov</span>(Years <span class="sc">~</span> Attr <span class="sc">*</span> Crime <span class="sc">+</span> Serious, <span class="at">data =</span> jury_data)</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Normality of residuals</span></span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a><span class="fu">shapiro.test</span>(jury_twoway_acov<span class="sc">$</span>residuals)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Shapiro-Wilk normality test

data:  jury_twoway_acov$residuals
W = 0.96895, p-value = 0.009416</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Homogeneity of variance</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>jury_data <span class="sc">%&gt;%</span></span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">levene_test</span>(Years <span class="sc">~</span> Attr <span class="sc">*</span> Crime, <span class="at">center =</span> <span class="st">"mean"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 4
    df1   df2 statistic      p
  &lt;int&gt; &lt;int&gt;     &lt;dbl&gt;  &lt;dbl&gt;
1     5   108      3.14 0.0111</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Linearity of covariate + homogeneity of regression slopes</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>jury_data <span class="sc">%&gt;%</span></span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(</span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">aes</span>(<span class="at">x =</span> Serious, <span class="at">y =</span> Years, <span class="at">colour =</span> Attr)</span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_jitter</span>() <span class="sc">+</span> </span>
<span id="cb27-8"><a href="#cb27-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Perceived seriousness of crime"</span>, <span class="at">y =</span> <span class="st">"Sentence length (Years)"</span>) <span class="sc">+</span></span>
<span id="cb27-9"><a href="#cb27-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> lm, <span class="at">se =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb27-10"><a href="#cb27-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>Crime)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="09-regressions-2_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>jury_data <span class="sc">%&gt;%</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">anova_test</span>(Years <span class="sc">~</span> Attr <span class="sc">*</span> Crime <span class="sc">*</span> Serious, <span class="at">effect.size =</span> <span class="st">"pes"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>ANOVA Table (type II tests)

              Effect DFn DFd      F        p p&lt;.05   pes
1               Attr   2 102  4.179 1.80e-02     * 0.076
2              Crime   1 102  0.403 5.27e-01       0.004
3            Serious   1 102 42.943 2.34e-09     * 0.296
4         Attr:Crime   2 102  2.955 5.70e-02       0.055
5       Attr:Serious   2 102  3.977 2.20e-02     * 0.072
6      Crime:Serious   1 102  0.658 4.19e-01       0.006
7 Attr:Crime:Serious   2 102  0.672 5.13e-01       0.013</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Output ANCOVA</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a><span class="fu">Anova</span>(jury_twoway_acov, <span class="at">type =</span> <span class="dv">3</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Anova Table (Type III tests)

Response: Years
            Sum Sq  Df F value    Pr(&gt;F)    
(Intercept)   5.32   1  0.5767   0.44927    
Attr         80.42   2  4.3592   0.01514 *  
Crime         4.43   1  0.4800   0.48991    
Serious     379.49   1 41.1423 3.938e-09 ***
Attr:Crime   49.30   2  2.6723   0.07370 .  
Residuals   986.95 107                      
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
</section>
</section>
<section id="hierarchical-regression" class="level2" data-number="9.2">
<h2 data-number="9.2" class="anchored" data-anchor-id="hierarchical-regression"><span class="header-section-number">9.2</span> Hierarchical regression</h2>
<p>Hierarchical regression is a form of multiple regression where we test the effects of predictors in <strong>blocks.</strong> The aim of doing a hierarchical regression is generally to test theoretical predictions about the effects of specific variables, especially before/after we control for other variables. The other aim is to explore how the <em>model</em> changes after we add additional predictors into the model.</p>
<p>The basic principle of a hierarchical regression is something like this:</p>
<ol type="1">
<li>Start by defining block 1, which is our basic regression model. This is the regression we start with. Run the regression defined in block 1.</li>
<li>Identify which variables will be entered into block 2, which is the first round of additional predictors</li>
<li>Run a second multiple regression with all predictors in block 2.</li>
<li>Compare block 1 with block 2 in terms of overall model fit.</li>
</ol>
<p>The choice of what variables to enter in which blocks must be guided by theory - in other words, you cannot simply add variables at random.</p>
<section id="example-1" class="level3" data-number="9.2.1">
<h3 data-number="9.2.1" class="anchored" data-anchor-id="example-1"><span class="header-section-number">9.2.1</span> Example</h3>
<p>Let’s return to the proneness to flow example introduced in the multiple regression section. As a reminder, here are our variables:</p>
<ul>
<li>Trait anxiety: broadly, refers to people’s tendency to feel anxious</li>
<li>Openness to experience: a personality trait that describes how likely people are to seek new experiences</li>
<li>DFS_Total: a measure of proneness to flow.</li>
<li>age: participant’s age.</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>flow_data <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="fu">here</span>(<span class="st">"data"</span>, <span class="st">"week_10"</span>, <span class="st">"w10_flow.csv"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 811 Columns: 6
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
dbl (6): id, age, GoldMSI, DFS_Total, trait_anxiety, openness

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
</div>
<p>In the first regressions module, we simply ran everything in one go as a multiple regression. Now let’s imagine we want to run this as a hierarchical regression, with the following blocks:</p>
<ul>
<li>Block 1: GOld MSI predicting proneness to flow (DFS_Total)</li>
<li>Block 2: Gold MSI and openness predicting proneness to flow</li>
<li>Block 3: Gold MSI, openness and trait anxiety predicting proneness to flow</li>
</ul>
<p>The assumption tests in multiple regressions are identical for hierarchical regressions.</p>
</section>
<section id="building-blocks-and-output" class="level3" data-number="9.2.2">
<h3 data-number="9.2.2" class="anchored" data-anchor-id="building-blocks-and-output"><span class="header-section-number">9.2.2</span> Building blocks and output</h3>
<p>Let’s start by building block 1. We can do this with <code>lm()</code> as per normal. I will call this <code>flow_block1</code>:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>flow_block1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(DFS_Total <span class="sc">~</span> GoldMSI, <span class="at">data =</span> flow_data)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>To build block 2, we simply need to create a new regression model with both predictors, as if we were running this in one go:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>flow_block2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(DFS_Total <span class="sc">~</span> GoldMSI <span class="sc">+</span> openness, <span class="at">data =</span> flow_data)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Finally, we do the same thing for block 3:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>flow_block3 <span class="ot">&lt;-</span> <span class="fu">lm</span>(DFS_Total <span class="sc">~</span> GoldMSI <span class="sc">+</span> openness <span class="sc">+</span> trait_anxiety, <span class="at">data =</span> flow_data)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Now let’s print the summary of each model. We can see in block 1 that Gold MSI scores significantly predict proneness to flow:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(flow_block1)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = DFS_Total ~ GoldMSI, data = flow_data)

Residuals:
     Min       1Q   Median       3Q      Max 
-14.1367  -2.4567   0.0448   2.2783  12.2886 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  16.3429     1.0848   15.06   &lt;2e-16 ***
GoldMSI       2.9231     0.1983   14.74   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 3.538 on 809 degrees of freedom
Multiple R-squared:  0.2118,    Adjusted R-squared:  0.2108 
F-statistic: 217.4 on 1 and 809 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>In Block 2, both the Gold MSI and openness are significant predictors of flow proneness.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(flow_block2)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = DFS_Total ~ GoldMSI + openness, data = flow_data)

Residuals:
     Min       1Q   Median       3Q      Max 
-14.3099  -2.3925   0.0643   2.2613  11.6213 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  14.6287     1.1912  12.281  &lt; 2e-16 ***
GoldMSI       2.7179     0.2061  13.185  &lt; 2e-16 ***
openness      0.4818     0.1425   3.382 0.000755 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 3.515 on 808 degrees of freedom
Multiple R-squared:  0.2228,    Adjusted R-squared:  0.2209 
F-statistic: 115.8 on 2 and 808 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Finally, in block 3 we can see that all three remain significant predictors. However, the effect of openness to experience has changed slightly (an unreliable heuristic for this is that the p-value has increased):</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(flow_block3)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = DFS_Total ~ GoldMSI + openness + trait_anxiety, 
    data = flow_data)

Residuals:
     Min       1Q   Median       3Q      Max 
-15.0424  -2.2409  -0.0931   2.1484  12.3474 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)   21.08246    1.33150  15.834   &lt;2e-16 ***
GoldMSI        2.66545    0.19623  13.583   &lt;2e-16 ***
openness       0.29958    0.13700   2.187   0.0291 *  
trait_anxiety -0.10662    0.01154  -9.237   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 3.345 on 807 degrees of freedom
Multiple R-squared:  0.2971,    Adjusted R-squared:  0.2945 
F-statistic: 113.7 on 3 and 807 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>On the next page we’ll talk about model comparison in a more formal manner. However, if we wanted to write these results up we would need to talk about the results from each block. For example:</p>
<p>A hierarchical regression was conducted to examine the effect</p>
</section>
</section>
<section id="comparing-models" class="level2" data-number="9.3">
<h2 data-number="9.3" class="anchored" data-anchor-id="comparing-models"><span class="header-section-number">9.3</span> Comparing models</h2>
<p>On the previous page, we ended up with three models relating to the flow data. That’s all well and good, and seeing how each model changed the predictors was valuable in its own right. But how do we actually… decide which model to run with?</p>
<section id="comparing-r2" class="level3" data-number="9.3.1">
<h3 data-number="9.3.1" class="anchored" data-anchor-id="comparing-r2"><span class="header-section-number">9.3.1</span> Comparing <span class="math inline">\(R^2\)</span></h3>
<p>The most commonly cited method of comparing between regression models is to examine their <span class="math inline">\(R^2\)</span> values, which you may recall is a measure of how much variance in the outcome is explained by the predictors.</p>
<p>This is easy enough to do visually. You can see the <span class="math inline">\(R^2\)</span> values in the output. We can extract this easily using the following code. Whenever we use <code>summary()</code> on an <code>lm()</code> model, the summary object will contain a variable for the <span class="math inline">\(R^2\)</span> that we can easily pull:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(flow_block1)<span class="sc">$</span>r.squared</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.211779</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(flow_block2)<span class="sc">$</span>r.squared</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.22278</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(flow_block3)<span class="sc">$</span>r.squared</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.2971018</code></pre>
</div>
</div>
<p>We can see that Block 3 has the highest <span class="math inline">\(R^2\)</span> at .297, meaning that the Block 3 model explains about 29.7% of the variance in the outcome. Block 2 explains 22.3% while Block 1 explains 21.2%. Therefore, based on this alone we might say that Block 2 explains only a little bit of extra variance in flow proneness than Block 1, while Block 3 explains substantially more - therefore, we should go with Block 3. However… <span class="math inline">\(R^2\)</span> will <em>always</em> increase with more predictors! The very fact that each additional predictor will explain more variance - even if only a tiny amount at a time - means that selecting based on <span class="math inline">\(R^2\)</span> alone will naturally favour models with more predictors. This isn’t necessarily a useful thing!</p>
</section>
<section id="nested-model-tests" class="level3" data-number="9.3.2">
<h3 data-number="9.3.2" class="anchored" data-anchor-id="nested-model-tests"><span class="header-section-number">9.3.2</span> Nested model tests</h3>
<p>This is a slightly more ‘formal’ test of whether a more complex model leads to a significant change in fit. This works by comparing <strong>nested</strong> models. Imagine model A and model B, two linear regressions fit on the same dataset. Model A has three predictors, and is the ‘full’ model of the thing we’re trying to the estimate. Model B drops one of the predictors from Model A, but keeps the other two. Model B is considered a <em>nested</em> model of Model A.</p>
<p>The principle of this test is based on the idea of seeing whether a nested (reduced) model is a significantly better fit than a full model. If a nested model is a better fit, the residual sums of squares will <em>decrease</em> - less residuals indicate better fit. The <code>anova()</code> test works on this principle, but in a sort of reverse way. Because we’re testing whether a model with <em>additional</em> predictors is a better fit, naturally we should expect that the ‘nested’ model (in this case, our original model) will be a <em>worse</em> fit than the new model. In that case, a significant result indicates that the more complex model is the better fit.</p>
<p>Nested model tests can be done with the <code>anova()</code> function from base R by simply giving it two model names in order. Let’s start by comparing Blocks 1 and 2:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(flow_block1, flow_block2)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Model 1: DFS_Total ~ GoldMSI
Model 2: DFS_Total ~ GoldMSI + openness
  Res.Df     RSS Df Sum of Sq      F    Pr(&gt;F)    
1    809 10124.2                                  
2    808  9982.9  1     141.3 11.437 0.0007547 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>And now between Blocks 2 and 3:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(flow_block2, flow_block3)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Model 1: DFS_Total ~ GoldMSI + openness
Model 2: DFS_Total ~ GoldMSI + openness + trait_anxiety
  Res.Df    RSS Df Sum of Sq      F    Pr(&gt;F)    
1    808 9982.9                                  
2    807 9028.3  1    954.62 85.329 &lt; 2.2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>From this, we can conclude that Block 2 is a better fit to the data than Block 1 (F(1, 808) = 11.437, <em>p</em> &lt; .001), and also that Block 3 is again a better fit than Block 2 (F(1, 807) = 85.329, <em>p</em> &lt; .001). Therefore, using this method we would consider using the model in Block 3 for interpretation, as this provides a better fit of the data. This sort of lines up with what we saw with the <span class="math inline">\(R^2\)</span> change (but this probably won’t always be the case).</p>
</section>
<section id="fit-indices" class="level3" data-number="9.3.3">
<h3 data-number="9.3.3" class="anchored" data-anchor-id="fit-indices"><span class="header-section-number">9.3.3</span> Fit indices</h3>
<p>An alternative approach is to use <strong>fit indices</strong>, which are various measures that essentially indicate how well a model fits the data. Importantly, unlike <span class="math inline">\(R^2\)</span> these measures penalise based on the complexity of the model - i.e.&nbsp;models with more predictors are penalised more due to their complexity.</p>
<p>Two of the most widely used fit indices are the <strong>Akaike Information Criterion (AIC)</strong> and the <strong>Bayesian Information Criterion (BIC)</strong>. They work similarly, but are just calculated in slightly different ways.</p>
<p>The AIC and BIC are calculated by:</p>
<p><span class="math display">\[
AIC = 2k -2 ln(\hat L)
\]</span></p>
<p><span class="math display">\[
BIC = k ln(n) - 2 ln (\hat L)
\]</span></p>
<p><span class="math inline">\(\hat L\)</span> is called the <strong>likelihood</strong>, which is a whole thing that we won’t dive too much into. However, <span class="math inline">\(2 ln (\hat L)\)</span> - or -2LL, or minus two log likelihood - goes by the name of <strong>deviance</strong> (as in deviation). Deviance is essentially the residual sum of squares, and thus serves as a measure of model fit.</p>
<p>R provides some really neat functions called - you guessed it - <code>AIC()</code> and <code>BIC()</code>. These will calculate the AIC and BIC values for every model name you give it. So, we can enter all of our values at once:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="fu">AIC</span>(flow_block1, flow_block2, flow_block3)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>            df      AIC
flow_block1  3 4354.820
flow_block2  4 4345.421
flow_block3  5 4265.907</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="fu">BIC</span>(flow_block1, flow_block2, flow_block3)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>            df      BIC
flow_block1  3 4368.915
flow_block2  4 4364.214
flow_block3  5 4289.398</code></pre>
</div>
</div>
<p>We can see that Block 3 has the lowest AIC and BIC values, meaning that it is the best fit.</p>
</section>
</section>
<section id="outliers" class="level2" data-number="9.4">
<h2 data-number="9.4" class="anchored" data-anchor-id="outliers"><span class="header-section-number">9.4</span> Outliers</h2>
<p>Up until this point, we’ve largely worked without considering outliers in our data. Outliers, however, are important for any and all analyses that we do, because they have an impact on our statistics.</p>
<p>An intuitive reason is simply because of the fact that many of our statistics involve differences between means - such as <em>t</em>-tests and ANOVAs - and means are susceptible to outliers. Consider the following set of values:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a>vector_b <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">3</span>, <span class="dv">2</span>, <span class="dv">4</span>, <span class="dv">2</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>If we take a mean, this is fairly straightforward:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(vector_b)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2.4</code></pre>
</div>
</div>
<p>However, imagine we have an outlier in one of our datapoints:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a>vector_b <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">3</span>, <span class="dv">2</span>, <span class="dv">50</span>, <span class="dv">2</span>)</span>
<span id="cb61-2"><a href="#cb61-2" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(vector_b)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 11.6</code></pre>
</div>
</div>
<p>Our estimate is now wildly different due to this outlier. Here’s another visualisation of this effect at play, with a simple regression model:</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="09-regressions-2_files/figure-html/unnamed-chunk-25-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="4200"></p>
</figure>
</div>
</div>
</div>
<p>You can see that in the graph on the left, there are no visible outliers, while the graph on the right has a very clear outlier (the dot at the very top). The resulting estimate of the correlation is vastly different - <em>r</em> = .57 without the outlier, vs <em>r</em> = .21 with it included!</p>
<p>In short, outliers have the potential to distort our estimates. Therefore, being able to systematically identify outliers and handle them is an important step in any analysis.</p>
<p>Although outliers are worth considering across all types of analyses, we’ll only consider them in context of regression models here for parity with Jamovi.</p>
<p>Aside from visual inspection, we have two main methods of identifying outliers in our regression models. For both examples, we will use <code>flow_block3</code> from the previous page.</p>
<section id="cooks-distance" class="level3" data-number="9.4.1">
<h3 data-number="9.4.1" class="anchored" data-anchor-id="cooks-distance"><span class="header-section-number">9.4.1</span> Cook’s distance</h3>
<p><strong>Cook’s distances</strong> are a method for identifying <strong>influential points</strong> in a regression model. The basic rationale is that if a point is highly influential, it has a large effect in shaping the overall parameter estimates in the regression model. Thus, points with high Cook’s distances values are worth looking into.</p>
<p>Cook’s distances can be easily calculated using the <code>cooks.distance()</code> function in base R. You just need to apply the name of the regression model (created using <code>lm()</code>):</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a>flow_cooksd <span class="ot">&lt;-</span> <span class="fu">cooks.distance</span>(flow_block3)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>This returns a singular vector of Cook’s distance values. We can then perform basic descriptives on this variable to get a sense of the range of Cook’s distance values:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(flow_cooksd)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.001356221</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sd</span>(flow_cooksd)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.00316087</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb68"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a><span class="fu">median</span>(flow_cooksd)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.0004290943</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb70"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb70-1"><a href="#cb70-1" aria-hidden="true" tabindex="-1"></a><span class="fu">min</span>(flow_cooksd)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 5.657846e-10</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb72"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb72-1"><a href="#cb72-1" aria-hidden="true" tabindex="-1"></a><span class="fu">max</span>(flow_cooksd)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.05169864</code></pre>
</div>
</div>
<p>If you prefer a tidyverse implementation, you can use the <code>augment()</code> function from the <code>broom</code> package (see <a href="#broom-augment">the appendix</a> for more information on <code>broom</code>). This returns a whole range of values, including fitted values, residuals (both of which are useful for Q-Q plots) and Cook’s distances:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb74"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb74-1"><a href="#cb74-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(broom)</span>
<span id="cb74-2"><a href="#cb74-2" aria-hidden="true" tabindex="-1"></a>flow_extra <span class="ot">&lt;-</span> <span class="fu">augment</span>(flow_block3)</span>
<span id="cb74-3"><a href="#cb74-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-4"><a href="#cb74-4" aria-hidden="true" tabindex="-1"></a>flow_extra</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 811 × 10
   DFS_Total GoldMSI openness trait_anxiety .fitted   .resid    .hat .sigma
       &lt;dbl&gt;   &lt;dbl&gt;    &lt;dbl&gt;         &lt;dbl&gt;   &lt;dbl&gt;    &lt;dbl&gt;   &lt;dbl&gt;  &lt;dbl&gt;
 1      30.5    5.61      5.5            54    31.9 -1.43    0.00203   3.35
 2      29.2    5.44      5              66    30.0 -0.793   0.00581   3.35
 3      27.5    5.06      4.5            58    29.7 -2.23    0.00479   3.35
 4      33      5.56      6              44    33.0 -0.00839 0.00144   3.35
 5      31      4         6.5            52    28.1  2.85    0.0105    3.35
 6      34.2    6         5.5            45    33.9  0.325   0.00297   3.35
 7      30.2    5.33      6.5            41    32.9 -2.61    0.00241   3.35
 8      34.5    6.11      6.5            36    35.5 -0.977   0.00414   3.35
 9      25      4.17      5.5            52    28.3 -3.30    0.00641   3.34
10      29.8    5.83      6              47    33.4 -3.66    0.00173   3.34
# ℹ 801 more rows
# ℹ 2 more variables: .cooksd &lt;dbl&gt;, .std.resid &lt;dbl&gt;</code></pre>
</div>
</div>
<p>The Cook’s distances are contained in the <code>.cooksd</code> column - note the full stop in front of the name is part of the column name.</p>
<p>As this returns a dataframe, we can then use normal tidyverse functions to wrangle this like any other dataframe.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb76"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb76-1"><a href="#cb76-1" aria-hidden="true" tabindex="-1"></a>flow_extra <span class="sc">%&gt;%</span></span>
<span id="cb76-2"><a href="#cb76-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb76-3"><a href="#cb76-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">mean =</span> <span class="fu">mean</span>(.cooksd),</span>
<span id="cb76-4"><a href="#cb76-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">sd =</span> <span class="fu">sd</span>(.cooksd),</span>
<span id="cb76-5"><a href="#cb76-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">median =</span> <span class="fu">median</span>(.cooksd),</span>
<span id="cb76-6"><a href="#cb76-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">min =</span> <span class="fu">min</span>(.cooksd),</span>
<span id="cb76-7"><a href="#cb76-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">max =</span> <span class="fu">max</span>(.cooksd)</span>
<span id="cb76-8"><a href="#cb76-8" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 5
     mean      sd   median      min    max
    &lt;dbl&gt;   &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;  &lt;dbl&gt;
1 0.00136 0.00316 0.000429 5.66e-10 0.0517</code></pre>
</div>
</div>
<p>Base R also provides an easy way of visualising Cook’s distances in regression models using <code>plot()</code>. To do this, you just feed in the name of the regression model (much like how you check for homoscedasticity during regression diagnostics). Note that <code>which = 4</code> must be specified.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb78"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb78-1"><a href="#cb78-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(flow_block3, <span class="at">which =</span> <span class="dv">4</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="09-regressions-2_files/figure-html/unnamed-chunk-30-1.png" class="img-fluid figure-img" width="4200"></p>
</figure>
</div>
</div>
</div>
<p>R will automatically label points that it thinks are influential data points in this plot. Based on this, data points 539, 627 and 789 might be worth a closer look.</p>
<p>How might you identify influential data points in general? There are <em>many</em> rules of thumb out there for Cook’s distances. Cook’s original guideline was to flag any point with a distance &gt; 1, but this might be relatively rare (note that our maximum distance in this model is 0.05!). Other rules include <span class="math inline">\(\frac{2k}{4}\)</span>, where <em>k</em> is the number of predictors in the model, <span class="math inline">\(\frac{4}{n}\)</span> where <em>n</em> = sample size, and <span class="math inline">\(2\sqrt{\frac{k}{n}}\)</span>. Truthfully, there is no singular metric that applies, so it’s up to you to choose one and apply it consistently.</p>
</section>
<section id="mahalanobis-distance-d2" class="level3" data-number="9.4.2">
<h3 data-number="9.4.2" class="anchored" data-anchor-id="mahalanobis-distance-d2"><span class="header-section-number">9.4.2</span> Mahalanobis’ distance, <span class="math inline">\(D^2\)</span></h3>
<p>Mahalanobis’ distance, <span class="math inline">\(D^2\)</span>, is a measure of <em>multivariate</em> outliers - ie. outliers across two or more predictors. The basic idea is that it is the literal distance between a ‘cloud’ of all of the predictors in your model. Outliers can be described as data points that are the furthest away from the centre of this ‘cloud’, quantified by having a high Mahalanobis distance.</p>
<p>Generating Mahalanobis’ distances in R is not difficult, and can be calculated using the <code>mahalanobis_distance()</code> function from the <code>rstatix</code>. This needs to be piped from the original dataset, and given the names of the <em>predictors</em> in the regression model.</p>
<p>In this case, as we are working with three predictors in this model - Gold-MSI scores, trait anxiety and openness - we give the names of these variables from our dataframe to this function.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb79"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb79-1"><a href="#cb79-1" aria-hidden="true" tabindex="-1"></a>flow_data <span class="ot">&lt;-</span> flow_data <span class="sc">%&gt;%</span></span>
<span id="cb79-2"><a href="#cb79-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mahalanobis_distance</span>(GoldMSI, trait_anxiety, openness)</span>
<span id="cb79-3"><a href="#cb79-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb79-4"><a href="#cb79-4" aria-hidden="true" tabindex="-1"></a>flow_data</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 811 × 8
      id   age GoldMSI DFS_Total trait_anxiety openness mahal.dist is.outlier
   &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt;     &lt;dbl&gt;         &lt;dbl&gt;    &lt;dbl&gt;      &lt;dbl&gt; &lt;lgl&gt;     
 1     1    24    5.61      30.5            54      5.5      0.649 FALSE     
 2     2    30    5.44      29.2            66      5        3.71  FALSE     
 3     3    25    5.06      27.5            58      4.5      2.88  FALSE     
 4     4    22    5.56      33              44      6        0.168 FALSE     
 5     5    18    4         31              52      6.5      7.48  FALSE     
 6     6    20    6         34.2            45      5.5      1.41  FALSE     
 7     7    23    5.33      30.2            41      6.5      0.954 FALSE     
 8     8    23    6.11      34.5            36      6.5      2.36  FALSE     
 9     9    20    4.17      25              52      5.5      4.20  FALSE     
10    10    25    5.83      29.8            47      6        0.399 FALSE     
# ℹ 801 more rows</code></pre>
</div>
</div>
<p>Note that this function will automatically flag whether a datapoint is an outlier. This is essentially done by calculating a critical Mahalanobis distance at <em>p</em> &lt; .001. Any datapoint that sits above this critical Mahalanobis distance is flagged as an outlier (see expanded details below under “How do Mahalanobis distances work?”)</p>
<p>We can view which datapoints are flagged as outliers by simply filtering our dataset using <code>filter()</code>:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb81"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb81-1"><a href="#cb81-1" aria-hidden="true" tabindex="-1"></a>flow_data <span class="sc">%&gt;%</span></span>
<span id="cb81-2"><a href="#cb81-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(is.outlier <span class="sc">==</span> <span class="cn">TRUE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 8
     id   age GoldMSI DFS_Total trait_anxiety openness mahal.dist is.outlier
  &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt;     &lt;dbl&gt;         &lt;dbl&gt;    &lt;dbl&gt;      &lt;dbl&gt; &lt;lgl&gt;     
1   378    32    4.83      29              38      2         21.0 TRUE      
2   528    24    5.72      30.2            65      2.5       17.7 TRUE      </code></pre>
</div>
</div>
<p>Here, we can see that participants 378 and 528 are multivariate outliers, and thus we may want to consider doing something about them.</p>
<details>
<summary>
How do Mahalanobis distances work?
</summary>
<div style="background-color: #f0f0f0;">
<p>The basic principle behind using Mahalanobis distances is basically the same as Cook’s distances: if a datapoint has a distance value greater than a specified cutoff, it is a multivariate outlier. The main difference is that <span class="math inline">\(D^2\)</span> is used for identifying multivariate outliers, as described above, and is empirically tested against a specified distribution (as opposed to Cook’s distances, where influential outliers are mainly identified on vibes).</p>
<p>Mahalanobis distances follow a chi-square distribution, with the degrees of freedom being equal to the number of predictors (<em>k</em>) in a model. The significance level for <span class="math inline">\(D^2\)</span> is conventionally set at <em>p</em> &lt; .001. In essence, any datapoint that has a <span class="math inline">\(D^2\)</span> greater than a cutoff point on a chi-square distribution, given df = <em>k</em> and at <em>p</em> &lt; .001, is considered a significant outlier.</p>
<p>To calculate Mahalanobis distances by hand, you can use the <code>mahalanobis()</code> function from base R. To do this, you need to give the function a dataframe with just the predictors in it.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb83"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb83-1"><a href="#cb83-1" aria-hidden="true" tabindex="-1"></a>flow_temp <span class="ot">&lt;-</span> flow_data <span class="sc">%&gt;%</span></span>
<span id="cb83-2"><a href="#cb83-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(GoldMSI, trait_anxiety, openness)</span>
<span id="cb83-3"><a href="#cb83-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb83-4"><a href="#cb83-4" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(flow_temp)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 3
  GoldMSI trait_anxiety openness
    &lt;dbl&gt;         &lt;dbl&gt;    &lt;dbl&gt;
1    5.61            54      5.5
2    5.44            66      5  
3    5.06            58      4.5
4    5.56            44      6  
5    4               52      6.5
6    6               45      5.5</code></pre>
</div>
</div>
<p>Then, feed it into the <code>mahalanobis()</code> function as below. Note the extra arguments; <code>colMeans(flow_temp)</code> specifies the means of the columns (i.e.&nbsp;the variables), and <code>cov(flow_temp)</code> generates the variance-covariance matrix between these variables.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb85"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb85-1"><a href="#cb85-1" aria-hidden="true" tabindex="-1"></a>mahal <span class="ot">&lt;-</span> <span class="fu">mahalanobis</span>(flow_temp, <span class="fu">colMeans</span>(flow_temp), <span class="fu">cov</span>(flow_temp))</span>
<span id="cb85-2"><a href="#cb85-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb85-3"><a href="#cb85-3" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(mahal)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.6491979 3.7060236 2.8816398 0.1675431 7.4849829 1.4083562</code></pre>
</div>
</div>
<p>Once we have done that we can leverage the properties of the chi-square distribution to calculate <em>p</em>-values for each Mahalanobis distance. Note that df = 3 here, as our original model had 3 predictors.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb87"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb87-1"><a href="#cb87-1" aria-hidden="true" tabindex="-1"></a>p <span class="ot">&lt;-</span> <span class="fu">pchisq</span>(mahal, <span class="at">df =</span> <span class="dv">3</span>, <span class="at">lower.tail =</span> <span class="cn">FALSE</span>)</span>
<span id="cb87-2"><a href="#cb87-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb87-3"><a href="#cb87-3" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(p)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.88508291 0.29500801 0.41023627 0.98265060 0.05794556 0.70357717</code></pre>
</div>
</div>
<p>Alternatively - and this is what <code>rstatix</code> does - you can calculate the Mahalanobis distance corresponding to <em>p</em> = .001, which will tell you the critical Mahalanobis distance value for a significant outlier.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb89"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb89-1"><a href="#cb89-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qchisq</span>(<span class="fl">0.999</span>, <span class="at">df =</span> <span class="dv">3</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 16.26624</code></pre>
</div>
</div>
<p>This means that any Mahalanobis distance above 16.27 will be significant.</p>
</div>
</details>
</section>
<section id="what-happens-if-there-is-an-outlier" class="level3" data-number="9.4.3">
<h3 data-number="9.4.3" class="anchored" data-anchor-id="what-happens-if-there-is-an-outlier"><span class="header-section-number">9.4.3</span> What happens if there is an outlier?</h3>
<p>Say that you’ve identified a bona fide outlier in your data. What do you do with it?</p>
<p>In these kinds of scenarios, the best-practice approach will most likely involve doing a <strong>sensitivity analysis</strong>. Sensitivity analyses are a general technique that broadly refer to testing your analyses under different conditions to see whether they hold under said conditions. The basic idea here is that you run <em>two</em> versions of your analyses:</p>
<ol type="1">
<li>First, a version <em>with</em> the outliers.</li>
<li>Next, a version <em>without</em> the outliers.</li>
</ol>
<p>The aim is to see whether the effect(s) of interest change as a result of excluding the outliers, and by how much.</p>
<p>Let’s see an example of this using the same model as before. Here is the original <code>flow_block3</code> model, just under a different name now:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb91"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb91-1"><a href="#cb91-1" aria-hidden="true" tabindex="-1"></a>flow_lm1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(DFS_Total <span class="sc">~</span> GoldMSI <span class="sc">+</span> trait_anxiety <span class="sc">+</span> openness, <span class="at">data =</span> flow_data)</span>
<span id="cb91-2"><a href="#cb91-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(flow_lm1)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = DFS_Total ~ GoldMSI + trait_anxiety + openness, 
    data = flow_data)

Residuals:
     Min       1Q   Median       3Q      Max 
-15.0424  -2.2409  -0.0931   2.1484  12.3474 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)   21.08246    1.33150  15.834   &lt;2e-16 ***
GoldMSI        2.66545    0.19623  13.583   &lt;2e-16 ***
trait_anxiety -0.10662    0.01154  -9.237   &lt;2e-16 ***
openness       0.29958    0.13700   2.187   0.0291 *  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 3.345 on 807 degrees of freedom
Multiple R-squared:  0.2971,    Adjusted R-squared:  0.2945 
F-statistic: 113.7 on 3 and 807 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Now, let’s remove the two outliers that we identified using Mahalanobis distances. These were participants 378 and 528. We will use <code>filter()</code> for simplicity.</p>
<p>The code below lets us remove specific rows. Let’s break down what this does:</p>
<ul>
<li>The exclamation mark <code>!</code> before <code>id</code> means “not” - i.e.&nbsp;do not do what comes next.</li>
<li>The <code>%in%</code> operator is a special operator in R that checks if a vector of values is present in another vector.</li>
<li>Here, <code>id %in% c(378, 528)</code> essentially means to see whether the <code>id</code> column has a 378 and 528 in it. By wrapping this in <code>filter()</code> we are essentially telling R to filer the rows where <code>id</code> equals 378 and 528.</li>
</ul>
<p>However, since all of that is preceded with the exclamation mark, the code is actually telling R to filter all the rows that are <em>not</em> <code>id</code> = 378 or 528 - in essence, it filters these rows <em>out</em>. It’s a bit complex, but it’s good to know as it applies to many scenarios!</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb93"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb93-1"><a href="#cb93-1" aria-hidden="true" tabindex="-1"></a>flow_no_outliers <span class="ot">&lt;-</span> flow_data <span class="sc">%&gt;%</span></span>
<span id="cb93-2"><a href="#cb93-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span>id <span class="sc">%in%</span> <span class="fu">c</span>(<span class="dv">378</span>, <span class="dv">528</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Now that we have a dataframe without the two outliers, let’s now refit our model. The only argument we need to change is the name of the dataset:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb94"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb94-1"><a href="#cb94-1" aria-hidden="true" tabindex="-1"></a>flow_lm2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(DFS_Total <span class="sc">~</span> GoldMSI <span class="sc">+</span> trait_anxiety <span class="sc">+</span> openness, <span class="at">data =</span> flow_no_outliers)</span>
<span id="cb94-2"><a href="#cb94-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(flow_lm2)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = DFS_Total ~ GoldMSI + trait_anxiety + openness, 
    data = flow_no_outliers)

Residuals:
     Min       1Q   Median       3Q      Max 
-15.0449  -2.2436  -0.1038   2.1526  12.3581 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)   21.15098    1.34199  15.761   &lt;2e-16 ***
GoldMSI        2.66601    0.19680  13.547   &lt;2e-16 ***
trait_anxiety -0.10694    0.01158  -9.232   &lt;2e-16 ***
openness       0.29029    0.14011   2.072   0.0386 *  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 3.348 on 805 degrees of freedom
Multiple R-squared:  0.2965,    Adjusted R-squared:  0.2939 
F-statistic: 113.1 on 3 and 805 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>We can see that even without the outliers, the pattern of results is very similar to the original model we had above. Therefore, in this kind of setting we don’t really gain anything by removing the outliers, and we might choose to keep the original model. Every participant lost is power lost, and the more information we have, the better! However, if your results do change substantially after excluding outliers then you will need to examine the differences carefully.</p>
<p>There are other methods that you could consider:</p>
<ul>
<li>Using a <em>non-parametric</em> test, which are not affected by outliers (see <a href="#nonpara">the section on non-parametric tests</a>)</li>
<li>Transforming the data to ‘un-outlier’ the outliers - this can be tricky to interpret</li>
</ul>
<p>Regardless, it is a good idea to report both versions of the model - with and without outliers - for transparency, to show that you have actively considered these residuals.</p>
</section>
</section>
<section id="partial-correlations" class="level2" data-number="9.5">
<h2 data-number="9.5" class="anchored" data-anchor-id="partial-correlations"><span class="header-section-number">9.5</span> Partial correlations</h2>
<section id="introduction-1" class="level3" data-number="9.5.1">
<h3 data-number="9.5.1" class="anchored" data-anchor-id="introduction-1"><span class="header-section-number">9.5.1</span> Introduction</h3>
<p>Recall that a correlation coefficient quantifies the strength of the relationship between two variables. That is a standard (zero-order) Pearson’s correlation coefficient, which is ubiquitous in just about any statistical analysis involving continuous variables.</p>
<p>There are many more types of correlation coefficients out there, some of which we talk about in this subject and others which we won’t touch. On this page, we’ll look at two extensions of Pearson’s correlation coefficent in particular: <strong>partial correlations</strong> and <strong>semipartial correlations</strong>. Both measures are useful specifically in regression contexts. On this page, we will start with partial correlations only, and move onto semipartials in the next.</p>
</section>
<section id="partial-correlations-1" class="level3" data-number="9.5.2">
<h3 data-number="9.5.2" class="anchored" data-anchor-id="partial-correlations-1"><span class="header-section-number">9.5.2</span> Partial correlations</h3>
<p>A <strong>partial correlation</strong> quantifies the relationship between variables X and Y, while controlling for variable Z. In essence, you can imagine that the effect of Z is ‘partialled out’ - or removed - from the correlation between X and Y. This is useful in situations just like the one described above - when you want to control for the effect of a certain variable when calculating a correlation coefficient.</p>
<p>The formula for a partial correlation is:</p>
<p><span class="math display">\[
r_{xy.z} = \frac{r_{xy} - (r_{xz} \times r_{yz})}{\sqrt{(1-r^2_{xz})(1-{r^2_{yz}})}}
\]</span></p>
<p>That is, you need to know the standard correlation between variables X and Y (<span class="math inline">\(r_{xy}\)</span>), the correlation between X and Z (<span class="math inline">\(r_{xz}\)</span>) and the correlation between Y and Z (<span class="math inline">\(r_{yz}\)</span>), and then plug them into the formula above.</p>
<p>Let’s come back to the flow data in Week 10 once again. Imagine we want to test the correlation between Gold MSI scores and flow proneness. However, we might suspect that openness to experience may play a role in the relationship between these variables - in other words, we expect openness to experience to affect both Gold-MSI scores and flow proneness. One thing we could do is to calculate a partial correlation between MSI scores and flow proneness while controlling for openness.</p>
<p>If we know the correlation between:</p>
<ul>
<li>MSI scores and flow proneness,</li>
<li>MSI scores and openness,</li>
<li>Flow proneness and openness,</li>
</ul>
<p>Then we can calculate partial correlations between MSI scores and flow proneness, controlling for openness.</p>
<p>In R, we can calculate both partial and semi-partial correlations using the <code>ppcor</code> package. For demonstration’s sake, we will filter the dataset so it only contains the three variables we are interested in here - Gold-MSI scores, openness and flow proneness - though it is not necessary to do this.</p>
<p>To calculate a partial correlation with a significant test, we can use the <code>pcor.test()</code> function. The function needs three arguments:</p>
<ul>
<li><code>x</code>: The first variable to correlate.</li>
<li><code>y</code>: The second variable to correlate.</li>
<li><code>z</code>: The control variable.</li>
</ul>
<p>The output will look something like this. This looks similar enough to a standard correlation output, and you can interpret it as such. The output shows the relationship between X (Gold-MSI) and Y (DFS Total, flow proneness), while controlling for the effect of openness to experience.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb96"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb96-1"><a href="#cb96-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ppcor)</span>
<span id="cb96-2"><a href="#cb96-2" aria-hidden="true" tabindex="-1"></a><span class="fu">pcor.test</span>(</span>
<span id="cb96-3"><a href="#cb96-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">x =</span> flow_data<span class="sc">$</span>GoldMSI,</span>
<span id="cb96-4"><a href="#cb96-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">y =</span> flow_data<span class="sc">$</span>DFS_Total,</span>
<span id="cb96-5"><a href="#cb96-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">z =</span> flow_data<span class="sc">$</span>openness</span>
<span id="cb96-6"><a href="#cb96-6" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>   estimate      p.value statistic   n gp  Method
1 0.4207818 4.274538e-36  13.18493 811  1 pearson</code></pre>
</div>
</div>
<p>Compare this to the standard correlation call below - we can see that even after controlling for openness the correlation is still significant, and doesn’t decrease by a huge amount (partial <em>r</em>(809) = .42, <em>p</em> &lt; .001).</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb98"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb98-1"><a href="#cb98-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Standard correlation</span></span>
<span id="cb98-2"><a href="#cb98-2" aria-hidden="true" tabindex="-1"></a><span class="fu">cor.test</span>(</span>
<span id="cb98-3"><a href="#cb98-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">x =</span> flow_data<span class="sc">$</span>GoldMSI,</span>
<span id="cb98-4"><a href="#cb98-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">y =</span> flow_data<span class="sc">$</span>DFS_Total</span>
<span id="cb98-5"><a href="#cb98-5" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's product-moment correlation

data:  flow_data$GoldMSI and flow_data$DFS_Total
t = 14.743, df = 809, p-value &lt; 2.2e-16
alternative hypothesis: true correlation is not equal to 0
95 percent confidence interval:
 0.4041563 0.5127911
sample estimates:
      cor 
0.4601945 </code></pre>
</div>
</div>
<p>To run multiple partial correlations, between variables, the <code>pcor()</code> function will compute these given a dataset. This will calculate partial correlations between pairs of variables, controlling for every other variable included in the call to <code>pcor()</code>. In the example below, we fuse <code>select()</code> to pull only the variables we are interested in and pipe this to <code>pcor()</code> - basically, we are giving <code>pcor()</code> a data frame with only the three variables of interest<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb100"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb100-1"><a href="#cb100-1" aria-hidden="true" tabindex="-1"></a>flow_data <span class="sc">%&gt;%</span></span>
<span id="cb100-2"><a href="#cb100-2" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(GoldMSI, openness, DFS_Total) <span class="sc">%&gt;%</span></span>
<span id="cb100-3"><a href="#cb100-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pcor</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>$estimate
            GoldMSI  openness DFS_Total
GoldMSI   1.0000000 0.2154726 0.4207818
openness  0.2154726 1.0000000 0.1181387
DFS_Total 0.4207818 0.1181387 1.0000000

$p.value
               GoldMSI     openness    DFS_Total
GoldMSI   0.000000e+00 5.794901e-10 4.274538e-36
openness  5.794901e-10 0.000000e+00 7.546911e-04
DFS_Total 4.274538e-36 7.546911e-04 0.000000e+00

$statistic
            GoldMSI openness DFS_Total
GoldMSI    0.000000 6.272218 13.184932
openness   6.272218 0.000000  3.381816
DFS_Total 13.184932 3.381816  0.000000

$n
[1] 811

$gp
[1] 1

$method
[1] "pearson"</code></pre>
</div>
</div>
<p>The way to read this table is to look at the <code>$estimate</code> part of the output for the correlations, and the <code>$p.value</code> for the corresponding <em>p</em>-value. We can see that the partial correlation between Gold-MSI scores and flow proneness is where the rows/columns for DFS_Total and GoldMSI meet.</p>
</section>
</section>
<section id="semipartial-correlations" class="level2" data-number="9.6">
<h2 data-number="9.6" class="anchored" data-anchor-id="semipartial-correlations"><span class="header-section-number">9.6</span> Semipartial correlations</h2>
<section id="semipartial-correlations-sr" class="level3" data-number="9.6.1">
<h3 data-number="9.6.1" class="anchored" data-anchor-id="semipartial-correlations-sr"><span class="header-section-number">9.6.1</span> Semipartial correlations (<em>sr</em>)</h3>
<p><strong>Semipartial correlations</strong> are similar in nature to partial correlations, with one key difference: the effect of the control variable Z is removed from X or Y, but not <em>both.</em> In other words, the controlling/partialling out of the effect of Z happens on only one of the two variables in the correlation.</p>
<p>This property of semipartial correlations makes it particularly useful in multiple regressions. Imagine we have a multiple regression with outcome Y and two predictors X and Z. The amount of variance explained in Y - this is <span class="math inline">\(R^2\)</span> - is a combination of the effects of individual predictors, and the relationship between predictors. Each predictor will contribute <em>unique</em> explained variance to that total amount of explained variance, and there will be some shared variance due to the relationship between predictors.</p>
<p>In other words, the <span class="math inline">\(R^2\)</span> for a given multiple regression can be broken down into:</p>
<ul>
<li>The unique variance explained by each predictor</li>
<li>The shared variance between predictors, due to the relationship between the predictors</li>
</ul>
<p>If we wanted to find out how much X <em>uniquely</em> contributes to outcome Y, we could first calculate a semipartial correlation between X and Y, controlling for Z’s effect on X. In essence, by removing Z’s effect on X only, we are isolating any effect of X on Y specifically, allowing us to examine how much X is contributing on its own. Likewise, if we wanted to find out the unique variance explained by Z, we would run another semipartial between Z and Y, controlling for X’s effect on Z.</p>
<p><strong>Squaring each sr value</strong> (i.e.&nbsp;calculate <span class="math inline">\(sr^2\)</span>), will give the <strong>unique amount of variance</strong> explained by predictor X, after controlling for all other variables. If <span class="math inline">\(sr^2\)</span> for variable X is 0.1, for instance, this means that <strong>10% of the variance in Y is uniquely estimated/contributed by X</strong>. In turn, if we calculate <span class="math inline">\(sr^2\)</span> values for each predictor, controlling for all other predictors, and subtract this from <span class="math inline">\(R^2\)</span>, this will give us the shared variance.</p>
<p>The diagram below summarises this info (shoutout to <a href="https://uq.pressbooks.pub/psychological-research-methods-workbook/chapter/activity-5-standard-and-hierarchical-multiple-regression-in-jamovi/">UQ</a>:</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="https://uq.pressbooks.pub/app/uploads/sites/108/2024/01/activity-5-figure-5.1-update.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="example-2" class="level3" data-number="9.6.2">
<h3 data-number="9.6.2" class="anchored" data-anchor-id="example-2"><span class="header-section-number">9.6.2</span> Example</h3>
<p>As an example, let’s look at a regression where Gold-MSI scores, openness to experience and trait anxiety predict flow proneness. In this model, <span class="math inline">\(R^2\)</span> is .297, meaning that 29.7% of the variance is explained by all three predictors together.</p>
<p>The <code>ppcor</code> package provides a function called <code>spcor.test()</code>, which works just like its <code>pcor.test()</code> cousin. The only difference is that because we are now partialling the effect of control variables from the <em>predictor</em> only, the order in which we enter <code>x</code> and <code>y</code> matters.</p>
<p>Namely, <code>x</code> must be the <em>outcome</em> variable, and <code>y</code> must be the <em>predictor</em> we are interested in controlling. This ensures that the control variables are correctly being removed from the predictor variable and not the outcome:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb102"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb102-1"><a href="#cb102-1" aria-hidden="true" tabindex="-1"></a><span class="fu">spcor.test</span>(</span>
<span id="cb102-2"><a href="#cb102-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">x =</span> flow_data<span class="sc">$</span>DFS_Total,</span>
<span id="cb102-3"><a href="#cb102-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">y =</span> flow_data<span class="sc">$</span>GoldMSI,</span>
<span id="cb102-4"><a href="#cb102-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">z =</span> flow_data[, <span class="fu">c</span>(<span class="st">"openness"</span>, <span class="st">"trait_anxiety"</span>)]</span>
<span id="cb102-5"><a href="#cb102-5" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>   estimate      p.value statistic   n gp  Method
1 0.4008732 1.391025e-32   12.4304 811  2 pearson</code></pre>
</div>
</div>
<p>Note that <code>flow_data[, c("openness", "trait_anxiety")]</code> is simply base R notation for selecting the columns named “openness” and “trait_anxiety” from the <code>flow_data</code> dataframe.</p>
<p>The semipartial correlation <em>sr</em> between Gold-MSI and flow proneness, controlling for the other two predictors (openness and trait anxiety) is <em>sr</em> = .401, <em>p</em> &lt; .001.</p>
<p>To calculate <span class="math inline">\(sr2\)</span> you will need to square the <em>sr</em> value above, which is thankfully easy enough in R:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb104"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb104-1"><a href="#cb104-1" aria-hidden="true" tabindex="-1"></a><span class="fl">0.4008732</span><span class="sc">^</span><span class="dv">2</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.1606993</code></pre>
</div>
</div>
<p>Squaring <em>sr</em> = .401 gives us <span class="math inline">\(sr^2\)</span> = 0.1697; this means that Gold-MSI scores uniquely explain 17% of the variance in flow proneness.</p>
</section>
<section id="calculating-all-sr2-values" class="level3" data-number="9.6.3">
<h3 data-number="9.6.3" class="anchored" data-anchor-id="calculating-all-sr2-values"><span class="header-section-number">9.6.3</span> Calculating all <span class="math inline">\(sr^2\)</span> values</h3>
<p>We could continue to use the <code>spcor.test()</code> function to calculate the other semipartial correlations for the other predictor and the outcome. However, just like <code>pcor()</code> we have an analogous function called <code>spcor()</code> that will calculate multiple semipartials in one go, using all of the variables in a provided dataframe. Like <code>pcor()</code>, the semipartials between two variables will be controlled for all other variables in the dataframe. In the output below, for example, the semipartial between DFS_Total and GoldMSI controls for both openness and trait_anxiety:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb106"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb106-1"><a href="#cb106-1" aria-hidden="true" tabindex="-1"></a>flow_data <span class="sc">%&gt;%</span></span>
<span id="cb106-2"><a href="#cb106-2" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(GoldMSI, trait_anxiety, openness, DFS_Total) <span class="sc">%&gt;%</span></span>
<span id="cb106-3"><a href="#cb106-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">spcor</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>$estimate
                GoldMSI trait_anxiety    openness  DFS_Total
GoldMSI       1.0000000    0.09414456  0.19909165  0.4120839
trait_anxiety 0.1025177    1.00000000 -0.10654766 -0.3051688
openness      0.2178267   -0.10705287  1.00000000  0.0725823
DFS_Total     0.4008732   -0.27262017  0.06453483  1.0000000

$p.value
                   GoldMSI trait_anxiety     openness    DFS_Total
GoldMSI       0.000000e+00  7.371908e-03 1.121410e-08 1.652919e-34
trait_anxiety 3.510562e-03  0.000000e+00 2.409483e-03 6.738338e-19
openness      3.815754e-10  2.296393e-03 0.000000e+00 3.901925e-02
DFS_Total     1.391025e-32  2.971642e-15 6.655997e-02 0.000000e+00

$statistic
                GoldMSI trait_anxiety  openness DFS_Total
GoldMSI        0.000000      2.686366  5.771281 12.847970
trait_anxiety  2.927722      0.000000 -3.044107 -9.103407
openness       6.340209     -3.058708  0.000000  2.067352
DFS_Total     12.430399     -8.049422  1.837118  0.000000

$n
[1] 811

$gp
[1] 2

$method
[1] "pearson"</code></pre>
</div>
</div>
<p>Recall that for a semipartial, we are interested in controlling the effect of other variables on the <em>predictor</em> and not the outcome. To obtain the corresponding values, we read across the row labelled with the <em>outcome</em> - i.e.&nbsp;<code>DFS_Total</code> - because this shows the semipartial correlation with each <em>predictor</em> in the columns.</p>
<p>We can see that the semipartial correlation between flow proneness and openness is not significant (<em>sr</em> = .07, <em>p</em> = .067), but the semipartial correlation with trait anxiety is (<em>sr</em> = -.27, <em>p</em> &lt; .001). Squaring these values respectively gives us the following values:</p>
<ul>
<li><span class="math inline">\(sr^2\)</span> for openness: 0.004 (i.e.&nbsp;0.4% of variance in flow proneness)</li>
<li><span class="math inline">\(sr^2\)</span> for trait anxiety: 0.075 (i.e.&nbsp;7.5% of variance in flow proneness)</li>
</ul>
<p>If we now add all of our <span class="math inline">\(sr^2\)</span> values together, we get 0.161 + 0.004 + 0.075 = 0.249, which means that <strong>24%</strong> of the variance in flow proneness is due to the unique effects of the individual predictors. Subtracting this number from the value for <span class="math inline">\(R^2\)</span> gives us 0.296 - 0.24 = 0.056, meaning that <strong>5.6%</strong> of the variance in flow proneness is explained by the shared variance of all three predictors.</p>
<p>Sometimes, it is useful to present <span class="math inline">\(sr^2\)</span> values for each predictor as part of a standard multiple regression table. This allows a reader to see how much each predictor is contributing to the variance in the outcome. in our case, we can say that Gold MSI scores explain the most variance in the outcome, while openness accounts for very little on its own.</p>


</section>
</section>
<section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes">
<hr>
<ol>
<li id="fn1"><p>Note that <code>ppcor</code> loads a package called <code>MASS</code>, which is used for a number of advanced statistical functions. <code>MASS</code> has its own <code>select()</code> function, which has a quirk of overwriting the tidyverse <code>select()</code> if <code>MASS</code>/<code>ppcor</code> is loaded after tidyverse; that is, any <code>select()</code> call you make might actually be <code>MASS::select()</code> (which won’t work for what you probably want to do) instead of <code>dplyr::select()</code> (which is the column selector). The solution is to either load <code>tidyverse</code> after everything else (if you’re sure this won’t break some other package’s function), or make explicit calls to <code>dplyr</code> using <code>dplyr::select()</code>, which is what I’ve done here.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./08-factorial-anovas.html" class="pagination-link" aria-label="Factorial ANOVAs">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Factorial ANOVAs</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./10-logistic.html" class="pagination-link" aria-label="Logistic regression">
        <span class="nav-page-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Logistic regression</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>Copyright 2026, Daniel Yeom</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
      <ul class="footer-items list-unstyled">
    <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/danyeom">
      <i class="bi bi-github" role="img">
</i> 
    </a>
  </li>  
</ul>
    </div>
  </div>
</footer>




</body></html>